module.exports = {
  apps: [
    {
      name: "web-app",
      cwd: "./packages/web",
      script: "src/server.ts",
      interpreter: "bun",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      restart_delay: 1000,
      env: {
        PORT: process.env.PORT || 4200,
        NODE_ENV: process.env.NODE_ENV || "production",
        DATABASE_URL: process.env.DATABASE_URL,
        DATABASE_AUTH_TOKEN: process.env.DATABASE_AUTH_TOKEN,
        S3_ENDPOINT: process.env.S3_ENDPOINT,
        S3_BUCKET: process.env.S3_BUCKET,
        S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
        S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
        AI_GATEWAY_BASE_URL: process.env.AI_GATEWAY_BASE_URL,
        AI_GATEWAY_API_KEY: process.env.AI_GATEWAY_API_KEY,
        BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
        AUTUMN_SECRET_KEY: process.env.AUTUMN_SECRET_KEY,
        WEBSITE_URL: process.env.WEBSITE_URL,
        RUNABLE_AUTH_ISSUER: process.env.RUNABLE_AUTH_ISSUER,
        RUNABLE_AUTH_CLIENT_ID: process.env.RUNABLE_AUTH_CLIENT_ID,
        RUNABLE_AUTH_CLIENT_SECRET: process.env.RUNABLE_AUTH_CLIENT_SECRET,
        RUNABLE_URL: process.env.RUNABLE_URL,
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
        TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
        TELEGRAM_ENABLED: process.env.TELEGRAM_ENABLED,
      },
    },
  ],
};
