import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { modules, questions, achievements } from "./database/schema";

const client = createClient({
  url: process.env.DATABASE_URL!,
  authToken: process.env.DATABASE_AUTH_TOKEN,
});
const db = drizzle(client);

async function seed() {
  console.log("🌱 Seeding database...");

  // Clear existing modules & questions to re-seed with correct order
  await db.delete(questions);
  await db.delete(modules);

  // Modules — lessonCount updated to match actual question count
  await db.insert(modules).values([
    { id: 1, title: "INTRODUCTION", subtitle: "TLS System Introduction", description: "Introduction to the Transponder Landing System — system overview, components, signal flow, power requirements, and safety protocols.", icon: "📖", color: "#1e90ff", order: 1, lessonCount: 10 },
    { id: 2, title: "OVERVIEW", subtitle: "TLS System Overview", description: "Comprehensive overview of the TLS system — architecture, subsystems, operational concepts, and system capabilities.", icon: "📡", color: "#00d4ff", order: 2, lessonCount: 10 },
    { id: 3, title: "INSTALLATION", subtitle: "Site & Equipment Installation", description: "Step-by-step installation procedures — site preparation, antenna setup, cable routing, power connections, and initial system checks.", icon: "🔩", color: "#0080ff", order: 3, lessonCount: 10 },
    { id: 4, title: "OPERATION", subtitle: "System Operation Procedures", description: "Operational procedures — startup sequences, normal operations, monitoring, ATC integration, and emergency handling.", icon: "🎮", color: "#1e90ff", order: 4, lessonCount: 10 },
    { id: 5, title: "CALIBRATION", subtitle: "System Calibration", description: "Calibration procedures — signal alignment, frequency calibration, flight inspection requirements, and performance verification.", icon: "📐", color: "#00bfff", order: 5, lessonCount: 10 },
    { id: 6, title: "MAINTENANCE", subtitle: "Maintenance Procedures", description: "Maintenance schedules, fault diagnosis, BITE systems, component replacement, and preventive maintenance procedures.", icon: "🔧", color: "#0066cc", order: 6, lessonCount: 10 },
    { id: 7, title: "CONTAINER & DEPLOYMENT", subtitle: "Transport & Deployment", description: "Container specifications, deployment procedures, site survey requirements, rapid setup for field operations.", icon: "📦", color: "#0080ff", order: 7, lessonCount: 8 },
    { id: 8, title: "PACKING INSTRUCTIONS", subtitle: "Packing & Storage", description: "Packing procedures, storage requirements, transport configurations, and equipment protection protocols.", icon: "🗃️", color: "#1e90ff", order: 8, lessonCount: 7 },
    { id: 9, title: "ATC QUICK GUIDE", subtitle: "ATC Operating Guide", description: "Quick reference guide for Air Traffic Controllers — TLS operating procedures, phraseology, and coordination requirements.", icon: "🛫", color: "#ffaa00", order: 9, lessonCount: 8 },
  ]);

  await db.insert(questions).values([

    // ── MODULE 1: INTRODUCTION (10 questions) ────────────────────────────────
    { moduleId: 1, question: "What does TLS stand for?", optionA: "Terminal Landing System", optionB: "Transponder Landing System", optionC: "Tactical Localizer System", optionD: "Track Landing Signal", correctOption: "b", explanation: "TLS stands for Transponder Landing System — a precision approach system that provides ILS-like guidance using the aircraft's transponder.", order: 1 },
    { moduleId: 1, question: "What is the primary purpose of the TLS system?", optionA: "Radar surveillance only", optionB: "Provide ILS-like precision approach guidance", optionC: "ATC communications", optionD: "Runway lighting control", correctOption: "b", explanation: "TLS provides ILS-equivalent lateral and vertical approach guidance to aircraft equipped with Mode C/S transponders.", order: 2 },
    { moduleId: 1, question: "What frequency band does TLS primarily operate in?", optionA: "HF (3–30 MHz)", optionB: "VHF (108–118 MHz)", optionC: "UHF (960–1215 MHz)", optionD: "SHF (3–30 GHz)", correctOption: "c", explanation: "TLS operates in the UHF band, using the aircraft's Mode C/S transponder for interrogation and response.", order: 3 },
    { moduleId: 1, question: "What is the primary advantage of TLS over conventional ILS?", optionA: "Lower cost of installation", optionB: "Portability and rapid deployment", optionC: "Higher signal frequency", optionD: "No need for FAA certification", correctOption: "b", explanation: "TLS can be rapidly deployed at airfields without permanent ILS infrastructure — a key advantage for military and temporary operations.", order: 4 },
    { moduleId: 1, question: "Which aircraft system does TLS interrogate?", optionA: "VOR receiver", optionB: "DME transponder", optionC: "SSR transponder (Mode C/S)", optionD: "TCAS unit", correctOption: "c", explanation: "TLS interrogates the aircraft's SSR transponder (Mode C or Mode S) to determine position and provide lateral/vertical guidance.", order: 5 },
    { moduleId: 1, question: "Who developed the TLS system?", optionA: "Raytheon", optionB: "Northrop Grumman", optionC: "Sievert Larsen (now part of Frequentis group)", optionD: "Thales Group", correctOption: "c", explanation: "TLS was developed by Sievert Larsen & Associates and is now part of the Frequentis group. It is widely used by military and civil aviation authorities worldwide.", order: 6 },
    { moduleId: 1, question: "What type of guidance signals does TLS transmit to the aircraft?", optionA: "VHF omni-directional signals", optionB: "ILS-equivalent localizer and glide slope signals", optionC: "GPS correction signals", optionD: "DME distance signals", correctOption: "b", explanation: "TLS generates and transmits ILS-equivalent localizer (lateral) and glide slope (vertical) signals directly to the approaching aircraft.", order: 7 },
    { moduleId: 1, question: "TLS is classified as which category of landing aid?", optionA: "Non-precision approach aid", optionB: "Precision approach aid (equivalent to ILS)", optionC: "Visual approach aid only", optionD: "Surveillance radar", correctOption: "b", explanation: "TLS provides precision approach guidance equivalent to a CAT I ILS, meaning it can support approaches down to ILS decision height minimums.", order: 8 },
    { moduleId: 1, question: "What is the minimum number of aircraft transponder modes TLS requires?", optionA: "Mode A only", optionB: "Mode C or Mode S", optionC: "Mode S only", optionD: "All modes A, C, and S simultaneously", correctOption: "b", explanation: "TLS requires the aircraft to be equipped with Mode C or Mode S transponder to allow the system to track position and provide guidance.", order: 9 },
    { moduleId: 1, question: "Which international standard governs TLS performance requirements?", optionA: "ICAO Annex 2", optionB: "ICAO Annex 10, Volume I", optionC: "FAR Part 91", optionD: "EUROCAE ED-90", correctOption: "b", explanation: "TLS must meet the performance requirements defined in ICAO Annex 10, Volume I for precision approach aids, ensuring compatibility with ILS-equipped aircraft.", order: 10 },

    // ── MODULE 2: OVERVIEW (10 questions) ────────────────────────────────────
    { moduleId: 2, question: "What type of approach guidance does TLS provide?", optionA: "Lateral only (azimuth)", optionB: "Vertical only (elevation)", optionC: "Both lateral and vertical (full precision)", optionD: "Advisory only (non-precision)", correctOption: "c", explanation: "TLS provides full precision approach guidance — both lateral (localizer equivalent) and vertical (glide slope equivalent) guidance.", order: 1 },
    { moduleId: 2, question: "What is the ILS localizer frequency range?", optionA: "75 MHz", optionB: "108.1–111.95 MHz (odd decimals)", optionC: "329.15–335.00 MHz", optionD: "960–1215 MHz", correctOption: "b", explanation: "ILS localizer operates on VHF frequencies between 108.10 and 111.95 MHz, using channels with odd decimal tenths.", order: 2 },
    { moduleId: 2, question: "What is the ILS glide slope frequency range?", optionA: "108–112 MHz", optionB: "329.15–335.00 MHz", optionC: "75 MHz", optionD: "1030 MHz", correctOption: "b", explanation: "The ILS glide slope operates on UHF frequencies between 329.15 and 335.00 MHz, paired with localizer frequencies.", order: 3 },
    { moduleId: 2, question: "At what angle is a standard ILS glide slope set?", optionA: "2°", optionB: "3°", optionC: "5°", optionD: "7°", correctOption: "b", explanation: "Standard ILS glide slope angle is 3° above horizontal, though it can range from 2° to 4.5° depending on terrain and obstacles.", order: 4 },
    { moduleId: 2, question: "What frequency does the ILS outer marker operate on?", optionA: "110.0 MHz", optionB: "75 MHz", optionC: "330 MHz", optionD: "1090 MHz", correctOption: "b", explanation: "All ILS marker beacons (outer, middle, inner) operate on 75 MHz. They are distinguished by tone modulation frequency and light color.", order: 5 },
    { moduleId: 2, question: "What modulation frequencies are used for ILS course deviation signals?", optionA: "400 Hz and 1000 Hz", optionB: "90 Hz and 150 Hz", optionC: "1020 Hz and 3000 Hz", optionD: "200 Hz and 400 Hz", correctOption: "b", explanation: "ILS (and TLS) use 90 Hz and 150 Hz tone modulation. The difference in depth of modulation (DDM) between these two tones indicates course deviation.", order: 6 },
    { moduleId: 2, question: "What does DDM stand for in ILS/TLS terminology?", optionA: "Digital Data Mode", optionB: "Difference in Depth of Modulation", optionC: "Directional Deviation Measurement", optionD: "Dual Distance Marker", correctOption: "b", explanation: "DDM stands for Difference in Depth of Modulation — the key parameter measuring how far an aircraft deviates from the approach centerline or glide path.", order: 7 },
    { moduleId: 2, question: "What are the main subsystems of the TLS?", optionA: "ASA, ESA, ATA, CALBIT, GTU, RCU, Interrogator", optionB: "Localizer, Glide Slope, Marker Beacon only", optionC: "VOR, DME, NDB", optionD: "Radar, Transponder, Display only", correctOption: "a", explanation: "TLS consists of: ASA (Azimuth Sensor), ESA (Elevation Sensor), ATA (Azimuth Tracking Antenna), CALBIT, GTU (Ground Transponder Unit), RCU (Remote Control Unit), and the Interrogator.", order: 8 },
    { moduleId: 2, question: "What is the role of the GTU (Ground Transponder Unit) in TLS?", optionA: "It receives GPS signals for positioning", optionB: "It processes sensor data and generates ILS-equivalent guidance signals", optionC: "It serves as the backup power supply", optionD: "It handles ATC voice communications", correctOption: "b", explanation: "The GTU is the central processing unit of TLS. It processes data from the ASA and ESA sensors to calculate aircraft position and generate the ILS-equivalent localizer and glide slope signals.", order: 9 },
    { moduleId: 2, question: "How does TLS track multiple aircraft simultaneously?", optionA: "It cannot — TLS handles only one aircraft at a time", optionB: "Using Mode S selective interrogation to address each aircraft by its unique code", optionC: "Using separate radar dishes for each aircraft", optionD: "Via GPS handoff between aircraft", correctOption: "b", explanation: "TLS uses Mode S selective interrogation to individually address each aircraft by its unique 24-bit ICAO address, allowing simultaneous guidance to multiple aircraft.", order: 10 },

    // ── MODULE 3: INSTALLATION (10 questions) ────────────────────────────────
    { moduleId: 3, question: "What DDM value defines the ILS glide path centerline?", optionA: "0.175 DDM", optionB: "0.0 DDM", optionC: "0.4 DDM", optionD: "0.25 DDM", correctOption: "b", explanation: "The glide path centerline is defined by 0.0 DDM (zero difference in depth of modulation between 90 Hz and 150 Hz signals).", order: 1 },
    { moduleId: 3, question: "The glide slope antenna is located:", optionA: "On the runway centerline at the threshold", optionB: "Offset from the runway, abeam the touchdown zone", optionC: "At the far end of the runway", optionD: "On top of the control tower", correctOption: "b", explanation: "The glide slope antenna is located beside the runway, typically 750–1250 feet from the threshold, offset laterally from centerline.", order: 2 },
    { moduleId: 3, question: "Which modulation frequency defines 'fly-up' on the glide slope?", optionA: "150 Hz dominates above path", optionB: "90 Hz dominates below path", optionC: "90 Hz dominates above path", optionD: "400 Hz carrier signal", correctOption: "c", explanation: "When 90 Hz dominates, the aircraft is above the glide path (fly-down signal). When 150 Hz dominates, the aircraft is below the glide path (fly-up signal).", order: 3 },
    { moduleId: 3, question: "What is the standard localizer course width at the threshold?", optionA: "±1° from centerline", optionB: "±2° from centerline — typically set so the course is 700 ft wide at threshold", optionC: "±5° from centerline", optionD: "±10° from centerline", correctOption: "b", explanation: "The localizer course width is set so the full deflection (0.155 DDM) occurs at approximately ±350 ft (±107 m) from centerline at the runway threshold — about ±2° total width.", order: 4 },
    { moduleId: 3, question: "What is the minimum site clearance required forward of the ASA antenna?", optionA: "No clearance required", optionB: "Clear line of sight to the runway threshold and approach corridor", optionC: "100 ft lateral clearance from buildings", optionD: "500 m from any metal structure", correctOption: "b", explanation: "The ASA must have a clear, unobstructed line of sight to the runway threshold and the entire approach corridor to accurately track aircraft transponder signals.", order: 5 },
    { moduleId: 3, question: "What tool is used during TLS installation to verify antenna leveling?", optionA: "GPS receiver", optionB: "Precision spirit level and theodolite", optionC: "Standard carpenter level", optionD: "Radio frequency analyzer only", correctOption: "b", explanation: "A precision spirit level and theodolite are used during TLS antenna installation to ensure all sensor elements are correctly leveled and aligned to the runway centerline.", order: 6 },
    { moduleId: 3, question: "During initial TLS installation, cables between units should be:", optionA: "Routed in any convenient path", optionB: "Routed in conduit, secured, and labeled at both ends", optionC: "Left exposed for easy inspection", optionD: "Connected wirelessly whenever possible", correctOption: "b", explanation: "All interconnecting cables must be routed through protective conduit, properly secured, and labeled at both ends to ensure reliable connections and ease of maintenance.", order: 7 },
    { moduleId: 3, question: "What is the typical power supply requirement for the TLS system?", optionA: "12V DC only", optionB: "Single-phase 110V AC", optionC: "Three-phase 480V AC", optionD: "Single or three-phase 208–240V AC with UPS backup", correctOption: "d", explanation: "TLS requires stable AC power (208–240V) with UPS backup to ensure continuous operation. Loss of power during an approach would be a critical safety issue.", order: 8 },
    { moduleId: 3, question: "After physical installation is complete, what is the FIRST operational check performed?", optionA: "Flight inspection immediately", optionB: "Bench test of individual units, then system power-on self-test (POST)", optionC: "Direct connection to ATC and live operation", optionD: "Calibration without any prior testing", correctOption: "b", explanation: "Before system integration, each unit undergoes individual bench testing. Once integrated, a system power-on self-test (POST) verifies all subsystems are communicating correctly before any calibration or flight checks.", order: 9 },
    { moduleId: 3, question: "Which document must be consulted for site-specific installation tolerances?", optionA: "The aircraft's flight manual", optionB: "TLS Installation and Maintenance Manual (IMM) and local ANPC regulations", optionC: "ICAO Annex 2 only", optionD: "The ATC ops manual", correctOption: "b", explanation: "The TLS Installation and Maintenance Manual (IMM) provides system-specific tolerances. Local ANPC/GACA regulations may impose additional site-specific requirements.", order: 10 },

    // ── MODULE 4: OPERATION (10 questions) ───────────────────────────────────
    { moduleId: 4, question: "What is the SSR Mode A used for?", optionA: "Altitude reporting", optionB: "Aircraft identification", optionC: "Emergency only", optionD: "Traffic collision avoidance", correctOption: "b", explanation: "Mode A provides aircraft identification — a 4-digit octal squawk code assigned by ATC.", order: 1 },
    { moduleId: 4, question: "What is the SSR Mode C used for?", optionA: "Aircraft identification", optionB: "Pressure altitude reporting", optionC: "Emergency beacon", optionD: "Datalink communications", correctOption: "b", explanation: "Mode C provides pressure altitude information encoded in Gillham code, transmitted automatically.", order: 2 },
    { moduleId: 4, question: "What frequency does the SSR interrogator transmit on?", optionA: "1030 MHz", optionB: "1090 MHz", optionC: "960 MHz", optionD: "75 MHz", correctOption: "a", explanation: "SSR interrogators transmit on 1030 MHz. Aircraft transponders reply on 1090 MHz.", order: 3 },
    { moduleId: 4, question: "What is the transponder reply frequency?", optionA: "1030 MHz", optionB: "960 MHz", optionC: "1090 MHz", optionD: "1215 MHz", correctOption: "c", explanation: "All transponders (Mode A/C/S) reply on 1090 MHz regardless of the interrogation mode.", order: 4 },
    { moduleId: 4, question: "What is the correct TLS startup sequence?", optionA: "Power on GTU → Interrogator → Sensors → RCU", optionB: "Power on all units simultaneously via master switch", optionC: "Follow the sequence specified in the TLS Operations Manual — typically RCU → GTU → sensors → interrogator", optionD: "Power on sensors first, then GTU last", correctOption: "c", explanation: "The TLS startup sequence is critical for safe operation. The Operations Manual specifies the exact order — typically bringing up the control unit (RCU) and processor (GTU) before enabling transmitters.", order: 5 },
    { moduleId: 4, question: "What squawk code is assigned to an aircraft for a TLS approach?", optionA: "7700 (emergency)", optionB: "7600 (comms failure)", optionC: "A specific discrete code assigned by ATC for TLS tracking", optionD: "1200 (VFR default)", correctOption: "c", explanation: "ATC assigns a specific discrete transponder code to each aircraft conducting a TLS approach, allowing the TLS to identify and track that specific aircraft among others in the area.", order: 6 },
    { moduleId: 4, question: "What does the RCU (Remote Control Unit) allow the operator to do?", optionA: "Communicate directly with the aircraft pilot", optionB: "Monitor system status, adjust parameters, and control TLS operation remotely", optionC: "Only displays GPS position data", optionD: "Controls runway lighting", correctOption: "b", explanation: "The RCU is the operator interface for TLS. It displays system health, allows parameter adjustments (glide angle, course alignment), and provides remote on/off control of system components.", order: 7 },
    { moduleId: 4, question: "During a TLS approach, if the system detects a signal anomaly, it should:", optionA: "Continue transmitting without alerting ATC", optionB: "Automatically flag the fault and the operator must assess whether to suspend the approach service", optionC: "Switch to GPS mode automatically", optionD: "Request the pilot to increase transponder power", correctOption: "b", explanation: "TLS has built-in integrity monitoring. Any detected anomaly triggers an alarm on the RCU. The operator must evaluate the fault and coordinate with ATC — the approach service may need to be suspended.", order: 8 },
    { moduleId: 4, question: "What is the maximum range at which TLS can typically track an aircraft on approach?", optionA: "2 NM", optionB: "5 NM", optionC: "20–30 NM (system dependent, typically 20 NM for guidance)", optionD: "100 NM", correctOption: "c", explanation: "TLS can detect transponder signals at ranges up to 30+ NM, but precision guidance is typically provided within 20 NM of the runway threshold — consistent with a standard ILS approach.", order: 9 },
    { moduleId: 4, question: "What ATC coordination is required before activating TLS for an approach?", optionA: "No coordination needed — TLS operates independently", optionB: "ATC must assign a squawk code to the aircraft and include TLS in the approach clearance", optionC: "Only pilot request is needed", optionD: "Weather check only", correctOption: "b", explanation: "ATC must assign a discrete squawk code, pass the frequency/identification to the crew, include TLS in the approach clearance, and coordinate with the TLS operator to ensure the system is active and tracking.", order: 10 },

    // ── MODULE 5: CALIBRATION (10 questions) ─────────────────────────────────
    { moduleId: 5, question: "How often should a full ILS/TLS calibration flight be conducted?", optionA: "Daily", optionB: "Weekly", optionC: "Every 90 days (or per ANPC schedule)", optionD: "Only after major maintenance", correctOption: "c", explanation: "Full flight calibration is typically required every 90 days, or per the applicable ANPC/ICAO maintenance schedule.", order: 1 },
    { moduleId: 5, question: "What parameter is verified during ILS localizer calibration?", optionA: "Antenna height", optionB: "Course width and alignment", optionC: "Power supply voltage", optionD: "Transponder code", correctOption: "b", explanation: "Localizer calibration verifies course width, course alignment, and clearance signals to ICAO Annex 10 standards.", order: 2 },
    { moduleId: 5, question: "What is the purpose of the CALBIT unit in TLS?", optionA: "It provides backup power to the GTU", optionB: "It is used during calibration to inject test signals and verify system accuracy", optionC: "It controls the runway lighting during calibration", optionD: "It records flight data for analysis", correctOption: "b", explanation: "CALBIT (Calibration Bit) is a specialized TLS unit that injects known test signals into the system during ground calibration, allowing technicians to verify that the signal processing chain is accurate without requiring an aircraft.", order: 3 },
    { moduleId: 5, question: "What tolerance is allowed for TLS glide slope angle deviation from the published value?", optionA: "±0.5°", optionB: "±10% of the nominal glide path angle (ICAO standard)", optionC: "±1.5°", optionD: "No tolerance — must be exact", correctOption: "b", explanation: "ICAO Annex 10 permits the glide path angle to vary within ±10% of the published nominal angle. For a 3° glide path, this means the angle must remain within 2.7°–3.3°.", order: 4 },
    { moduleId: 5, question: "What is 'course structure' in the context of ILS/TLS localizer calibration?", optionA: "The physical layout of the runway", optionB: "Bends or irregularities in the DDM signal as an aircraft flies the approach course", optionC: "The filing of the approach procedure by ANPC", optionD: "The antenna structure dimensions", correctOption: "b", explanation: "Course structure refers to bends or irregularities in the DDM signal along the approach path. Excessive course structure causes the aircraft instruments to deviate unnecessarily, which is unsafe for precision approaches.", order: 5 },
    { moduleId: 5, question: "Who is authorized to perform a TLS flight calibration in Saudi Arabia?", optionA: "Any licensed pilot", optionB: "ANPC-authorized flight inspection crews using certified inspection aircraft", optionC: "The TLS operator technician alone", optionD: "Any military aircraft with Mode S", correctOption: "b", explanation: "Flight calibration must be performed by ANPC-authorized flight inspection crews (e.g., Saudi ANPC or contracted agencies) using specially equipped and certified inspection aircraft.", order: 6 },
    { moduleId: 5, question: "After a TLS antenna has been physically moved or realigned, what is mandatory?", optionA: "A new flight inspection to re-certify the system", optionB: "Only a software recalibration via RCU", optionC: "Visual confirmation by the tower controller", optionD: "No action needed if moved less than 10 cm", correctOption: "a", explanation: "Any physical movement or realignment of TLS antennas voids the existing calibration. A full flight inspection is mandatory before the system can be used for approach guidance.", order: 7 },
    { moduleId: 5, question: "What is the TLS ground calibration procedure performed BEFORE a flight inspection?", optionA: "No ground calibration is needed", optionB: "Verify physical installation, run system self-tests, perform CALBIT checks, and confirm signal parameters on the RCU", optionC: "Replace all cables and components", optionD: "Switch to backup mode and test manually", correctOption: "b", explanation: "Before a flight inspection, technicians verify physical installation integrity, run system self-tests, use CALBIT to confirm signal processing accuracy, and verify all parameters (angle, width, alignment) on the RCU.", order: 8 },
    { moduleId: 5, question: "What does a 'false course' indicate during localizer calibration?", optionA: "An aircraft off the approach path", optionB: "A spurious DDM indication that could mislead pilots away from the runway centerline", optionC: "A temporary GPS outage", optionD: "An incorrect squawk code assignment", correctOption: "b", explanation: "A false course is an area where the DDM signal incorrectly indicates 'on course' at a position that is actually off the centerline. This is a critical safety defect that must be eliminated before the system is commissioned.", order: 9 },
    { moduleId: 5, question: "The TLS glide path is considered out of tolerance when the measured angle differs from published by more than:", optionA: "0.01°", optionB: "The 10% ICAO tolerance band (e.g., >0.3° for a 3° nominal)", optionC: "5°", optionD: "The tolerance is unlimited above the path", correctOption: "b", explanation: "ICAO Annex 10 specifies a ±10% tolerance on glide path angle. For a 3° nominal glide path, the measured angle must remain within 2.7°–3.3°. Exceeding this requires immediate corrective action.", order: 10 },

    // ── MODULE 6: MAINTENANCE (10 questions) ─────────────────────────────────
    { moduleId: 6, question: "What does BITE stand for in avionics maintenance?", optionA: "Basic Integrated Test Equipment", optionB: "Built-In Test Equipment", optionC: "Binary Input Terminal Engine", optionD: "Baseline Integrity Test Engine", correctOption: "b", explanation: "BITE stands for Built-In Test Equipment — self-diagnostic systems that continuously monitor equipment health.", order: 1 },
    { moduleId: 6, question: "What is the purpose of preventive maintenance?", optionA: "Fix faults after failure", optionB: "Prevent failures before they occur", optionC: "Reduce power consumption", optionD: "Upgrade software", correctOption: "b", explanation: "Preventive maintenance is scheduled work done to prevent failures, extend equipment life, and maintain performance standards.", order: 2 },
    { moduleId: 6, question: "How often should TLS antenna connectors be inspected for corrosion and tightness?", optionA: "Every 5 years", optionB: "Per the maintenance schedule — typically every 3–6 months in harsh environments", optionC: "Only when a fault is detected", optionD: "Once at installation, no further checks needed", correctOption: "b", explanation: "In a desert/military environment, connector corrosion and loosening are common failure modes. The maintenance schedule typically requires 3–6 monthly inspection cycles depending on environmental conditions.", order: 3 },
    { moduleId: 6, question: "What is the correct procedure when a TLS BITE alarm is triggered?", optionA: "Ignore it and wait for the system to self-heal", optionB: "Log the fault code, isolate the affected unit, and follow the fault isolation procedure in the IMM", optionC: "Immediately replace all units", optionD: "Call the manufacturer hotline first without any diagnostics", correctOption: "b", explanation: "BITE alarms provide fault codes that identify the affected subsystem. The technician must log the code, isolate the faulty unit, and follow the Fault Isolation Procedures (FIP) in the Installation and Maintenance Manual (IMM).", order: 4 },
    { moduleId: 6, question: "What is the primary purpose of cable continuity testing during maintenance?", optionA: "To measure signal frequency", optionB: "To verify cables are unbroken and properly terminated with correct impedance", optionC: "To test the power supply voltage", optionD: "To align the antenna", correctOption: "b", explanation: "Cable continuity testing verifies that signal cables are unbroken, properly shielded, and terminated with the correct characteristic impedance (typically 50Ω for RF cables), preventing signal reflections and losses.", order: 5 },
    { moduleId: 6, question: "When replacing a TLS component, which document must be consulted first?", optionA: "The aircraft's flight manual", optionB: "The TLS Installation and Maintenance Manual (IMM) component replacement procedure", optionC: "A general electronics manual", optionD: "No documentation needed for simple replacements", correctOption: "b", explanation: "All component replacements must follow the IMM replacement procedure to ensure correct re-installation, re-alignment, and post-replacement testing before returning the system to service.", order: 6 },
    { moduleId: 6, question: "What does a high SWR (Standing Wave Ratio) reading indicate in the TLS RF system?", optionA: "The system is transmitting at full power", optionB: "Impedance mismatch causing signal reflections — likely a faulty connector, cable, or antenna", optionC: "Normal operating condition", optionD: "GPS interference", correctOption: "b", explanation: "A high SWR indicates that the transmitted RF signal is being reflected back due to impedance mismatch. This reduces effective radiated power and can damage the transmitter. Common causes are faulty connectors, damaged cables, or antenna damage.", order: 7 },
    { moduleId: 6, question: "After completing TLS maintenance that involved any RF components, what must be done?", optionA: "Return to service immediately — no checks needed", optionB: "Perform system self-test (BITE), verify RF parameters, and conduct ground functional checks before returning to service", optionC: "Wait 24 hours for the system to stabilize", optionD: "Only check the power supply", correctOption: "b", explanation: "After RF maintenance, the system self-test must confirm no fault codes, RF parameters (power level, SWR, frequency) must be verified, and a full ground functional check must confirm correct signal output before the system returns to service.", order: 8 },
    { moduleId: 6, question: "What environmental factor most commonly affects TLS antenna performance in Saudi Arabia?", optionA: "Heavy rainfall", optionB: "Sand and dust accumulation causing signal attenuation and connector degradation", optionC: "Freezing temperatures", optionD: "High humidity only", correctOption: "b", explanation: "In Saudi Arabia's desert environment, sand and dust accumulation is the primary environmental threat to TLS antennas and connectors. Regular cleaning and protection of antenna elements and connectors is essential for reliable operation.", order: 9 },
    { moduleId: 6, question: "What is the recommended action if TLS ground equipment is struck by lightning?", optionA: "Resume operation immediately if no BITE alarms are present", optionB: "Conduct a full inspection of surge protection devices, cables, and electronic units before returning to service", optionC: "Replace only the antenna", optionD: "Lightning has no effect on ground-based equipment", correctOption: "b", explanation: "Even with lightning protection, a strike can cause latent damage to surge protection devices, cable shielding, and sensitive electronics. A comprehensive inspection of all components is mandatory before returning the system to operational service.", order: 10 },

    // ── MODULE 7: CONTAINER & DEPLOYMENT (8 questions) ───────────────────────
    { moduleId: 7, question: "What is the primary advantage of a containerized TLS system?", optionA: "Lower power consumption", optionB: "Rapid deployment to forward locations", optionC: "Higher signal accuracy", optionD: "Reduced maintenance", correctOption: "b", explanation: "Containerized TLS systems can be rapidly transported and deployed to temporary or forward operating locations.", order: 1 },
    { moduleId: 7, question: "What type of vehicle is typically used to transport the TLS container?", optionA: "Standard passenger vehicle", optionB: "Flatbed truck or military heavy transport vehicle with appropriate load rating", optionC: "Helicopter only", optionD: "Rail transport only", correctOption: "b", explanation: "The TLS container requires a flatbed truck or equivalent heavy transport vehicle with sufficient load capacity. Military deployments may use dedicated logistics vehicles (e.g., HEMTT) rated for the container's weight.", order: 2 },
    { moduleId: 7, question: "What is performed as part of the site survey BEFORE TLS deployment?", optionA: "Nothing — any flat area is suitable", optionB: "Evaluation of runway orientation, terrain clearances, power availability, obstructions, and soil bearing capacity", optionC: "Only GPS coordinate verification", optionD: "Weather forecast check only", correctOption: "b", explanation: "A thorough site survey evaluates runway orientation and approach path, terrain and obstruction clearances, available power, communication infrastructure, soil bearing capacity for equipment placement, and local environmental factors.", order: 3 },
    { moduleId: 7, question: "How long does a standard TLS field deployment typically take with a trained crew?", optionA: "Less than 1 hour", optionB: "Approximately 4–8 hours for mechanical setup; full commissioning including calibration takes longer", optionC: "3–5 days minimum", optionD: "It cannot be deployed — TLS is permanently installed only", correctOption: "b", explanation: "A trained TLS crew can complete mechanical deployment (offloading, positioning, leveling, cable connections) in approximately 4–8 hours. Full operational commissioning including calibration and flight inspection takes additional time.", order: 4 },
    { moduleId: 7, question: "What is the purpose of the leveling jacks on the TLS antenna mounts?", optionA: "They are aesthetic — no functional purpose", optionB: "To precisely level the antenna assembly to ensure accurate sensor alignment on uneven terrain", optionC: "To raise antennas above obstacles", optionD: "To lock the container to the ground", correctOption: "b", explanation: "TLS sensor accuracy is highly sensitive to antenna tilt. Leveling jacks allow precise antenna leveling even on uneven terrain, ensuring the sensor reference plane is correctly established for accurate position calculation.", order: 5 },
    { moduleId: 7, question: "During TLS deployment, the ASA and ESA antennas must be aligned to:", optionA: "Magnetic north", optionB: "The runway centerline extended — the approach course", optionC: "True north only", optionD: "The nearest VOR station", correctOption: "b", explanation: "The TLS ASA and ESA antennas must be aligned precisely to the extended runway centerline (approach course). Misalignment directly causes lateral and vertical course errors for approaching aircraft.", order: 6 },
    { moduleId: 7, question: "What is the minimum ground clearance required for TLS antenna elements from the terrain surface?", optionA: "No minimum — place on the ground", optionB: "As specified in the TLS deployment manual — sufficient height to maintain clear signal path to approaching aircraft", optionC: "Exactly 3 meters above ground in all cases", optionD: "Antenna height does not affect performance", correctOption: "b", explanation: "Antenna height requirements are specified in the TLS deployment manual and are based on the approach geometry. Insufficient height can cause multipath reflections or signal blockage that degrade guidance accuracy.", order: 7 },
    { moduleId: 7, question: "After deployment, before the first live approach, the TLS operator must:", optionA: "Begin operations immediately", optionB: "Complete all BITE checks, ground calibration, and coordinate with ATC and ANPC for any required flight inspection", optionC: "Only verify power is connected", optionD: "Submit a written report and wait 30 days", correctOption: "b", explanation: "Before any live approach service, a full post-deployment checklist must be completed: BITE verification, ground calibration, RCU parameter confirmation, ATC coordination, and ANPC authorization (which may require a flight inspection).", order: 8 },

    // ── MODULE 8: PACKING INSTRUCTIONS (7 questions) ─────────────────────────
    { moduleId: 8, question: "What is the primary purpose of proper equipment packing?", optionA: "Reduce weight", optionB: "Protect equipment during transport and storage", optionC: "Improve signal performance", optionD: "Reduce cost", correctOption: "b", explanation: "Proper packing procedures protect sensitive TLS components from damage during transport, storage, and handling.", order: 1 },
    { moduleId: 8, question: "What type of packaging is required for TLS RF components and antenna elements?", optionA: "Standard cardboard boxes", optionB: "Anti-static bags inside rigid cases with foam cutouts — as specified in the TLS packing list", optionC: "Wrapped in cloth only", optionD: "No special packaging required", correctOption: "b", explanation: "TLS RF components and antenna elements are sensitive to electrostatic discharge (ESD) and physical shock. They must be packed in anti-static bags inside rigid, shock-absorbing cases with foam cutouts sized to each component.", order: 2 },
    { moduleId: 8, question: "Before packing TLS equipment for storage, what preservation step is mandatory?", optionA: "No preparation needed", optionB: "Clean all components, apply corrosion protection to metal surfaces, seal connector ports with dust caps", optionC: "Only remove batteries", optionD: "Power on for a final test only", correctOption: "b", explanation: "Before storage, all components must be cleaned, metal surfaces (especially connectors and antenna elements) treated with corrosion inhibitor, and all connector ports sealed with protective caps to prevent moisture and dust ingress.", order: 3 },
    { moduleId: 8, question: "What documentation must accompany a TLS system being packed for transport?", optionA: "No documentation required", optionB: "Packing list, equipment condition report, and any outstanding maintenance discrepancies", optionC: "Only the equipment serial numbers", optionD: "The pilot's flight plan only", correctOption: "b", explanation: "A complete packing list verifying all components are accounted for, an equipment condition report noting any defects or maintenance status, and documentation of outstanding discrepancies must accompany the packed system.", order: 4 },
    { moduleId: 8, question: "When packing TLS cables for storage, the correct method is:", optionA: "Wrap as tightly as possible to save space", optionB: "Coil loosely to the manufacturer's specified minimum bend radius, secured with Velcro ties — not cable ties", optionC: "Bundle with metal wire", optionD: "Stretch straight in a long container", correctOption: "b", explanation: "Cables must be coiled to the manufacturer's specified minimum bend radius to prevent internal conductor damage. Velcro ties are used instead of cable ties to avoid crushing the cable jacket and shielding.", order: 5 },
    { moduleId: 8, question: "What environmental conditions should TLS equipment storage areas maintain?", optionA: "Any available space is acceptable", optionB: "Controlled temperature (10–35°C), low humidity (<60% RH), clean, and free from vibration", optionC: "Hot and dry environment only", optionD: "No requirements — equipment is fully weatherproof", correctOption: "b", explanation: "TLS equipment contains sensitive electronics. Storage should be in a temperature-controlled (10–35°C), low-humidity (<60% RH), clean environment free from vibration to prevent component degradation during storage.", order: 6 },
    { moduleId: 8, question: "How should TLS antennas be oriented when packed in their shipping crates?", optionA: "Any orientation is acceptable", optionB: "As indicated by orientation arrows/labels on the crate — typically horizontal with fragile elements protected", optionC: "Always vertical regardless of crate design", optionD: "Orientation is irrelevant for antennas", correctOption: "b", explanation: "Shipping crates for TLS antennas are designed and labeled for a specific orientation. Incorrect orientation can cause antenna elements to contact crate walls, leading to damage. Always follow the orientation markings.", order: 7 },

    // ── MODULE 9: ATC QUICK GUIDE (8 questions) ───────────────────────────────
    { moduleId: 9, question: "ANPC stands for:", optionA: "Aviation Navigation Procedures Certification", optionB: "Air Navigation and Procedures Committee", optionC: "Advanced Navigation Precision Control", optionD: "Aviation and Navigation Procedures Commission", correctOption: "b", explanation: "ANPC stands for Air Navigation and Procedures Committee — the Saudi authority governing aviation navigation standards.", order: 1 },
    { moduleId: 9, question: "Who is responsible for ANPC certification in Saudi Arabia?", optionA: "GACA (General Authority of Civil Aviation)", optionB: "RSAF Technical Command", optionC: "Ministry of Transport", optionD: "ICAO directly", correctOption: "a", explanation: "GACA (General Authority of Civil Aviation) oversees ANPC certification standards in the Kingdom of Saudi Arabia.", order: 2 },
    { moduleId: 9, question: "When an ATC controller issues a TLS approach clearance, what specific information must be included?", optionA: "Only the runway number", optionB: "Runway, TLS frequency, approach type, and the assigned transponder squawk code", optionC: "Weather conditions only", optionD: "Aircraft registration number only", correctOption: "b", explanation: "A complete TLS approach clearance must include: the runway in use, the TLS ILS-equivalent frequency to tune, the approach type (TLS approach), and the discrete transponder squawk code for TLS tracking.", order: 3 },
    { moduleId: 9, question: "What is the correct ATC phraseology to clear an aircraft for a TLS approach?", optionA: "\"Cleared radar approach\"", optionB: "\"[Callsign], cleared TLS approach runway [XX], squawk [code]\"", optionC: "\"[Callsign], cleared ILS approach\" (TLS is identical to ILS phraseology)", optionD: "\"[Callsign], radar vectors, report final\"", correctOption: "b", explanation: "TLS has its own specific phraseology. The controller must specify 'TLS approach' (not ILS), the runway, and the specific squawk code that the TLS system will use to track the aircraft.", order: 4 },
    { moduleId: 9, question: "If TLS service is suspended during an approach, what must the ATC controller do immediately?", optionA: "Continue the approach — the aircraft has visual contact", optionB: "Immediately advise the pilot, issue a go-around instruction if necessary, and offer an alternative approach", optionC: "Wait to see if the system recovers", optionD: "Only log the event for later review", correctOption: "b", explanation: "TLS service suspension during an approach is a critical safety event. The controller must immediately notify the pilot, issue a go-around if the aircraft is inside the decision altitude, and provide an alternative approach or diversion.", order: 5 },
    { moduleId: 9, question: "What weather minima apply to a TLS approach?", optionA: "Same as VFR only", optionB: "As published in the specific TLS approach procedure for that runway — typically equivalent to ILS CAT I minima", optionC: "No weather minima — TLS works in all conditions", optionD: "50 ft decision height in all cases", correctOption: "b", explanation: "TLS approach minima are published in the approach plate for the specific procedure. They are typically equivalent to ILS CAT I (typically 200 ft DH / 550 m RVR), but may vary based on the specific installation and local regulations.", order: 6 },
    { moduleId: 9, question: "What is the TLS operator's responsibility during an active approach?", optionA: "No responsibility once the approach is initiated", optionB: "Monitor system status continuously, alert ATC immediately to any fault, and be ready to suspend service", optionC: "Only record data for post-flight analysis", optionD: "Communicate directly with the pilot on guard frequency", correctOption: "b", explanation: "During any active TLS approach, the operator must maintain continuous monitoring of system parameters on the RCU. Any anomaly must be immediately reported to ATC so appropriate action can be taken for the safety of the aircraft.", order: 7 },
    { moduleId: 9, question: "How does TLS service differ from a conventional ILS for the pilot?", optionA: "There is no difference — pilots fly TLS identically to ILS using their existing instruments", optionB: "Pilots tune the assigned TLS frequency (ILS-equivalent), use their normal ILS instruments, but must squawk the assigned code", optionC: "Pilots must use a special TLS receiver", optionD: "TLS requires visual reference at all times", correctOption: "b", explanation: "From the pilot's perspective, TLS guidance appears on standard ILS instruments (CDI, glide slope needle). The only difference is that pilots must squawk the specific code assigned by ATC so the TLS can identify and track their aircraft.", order: 8 },

  ]);

  // Achievements
  await db.insert(achievements).values([
    { key: "first_lesson", name: "First Lesson", description: "Completed your first lesson", icon: "⚡", color: "#00ff88", xpReward: 50 },
    { key: "module_1_complete", name: "Introduction Complete", description: "Completed TLS Introduction", icon: "📖", color: "#1e90ff", xpReward: 200 },
    { key: "module_6_complete", name: "Maintenance Expert", description: "Completed Maintenance module", icon: "🔧", color: "#00d4ff", xpReward: 200 },
    { key: "module_9_complete", name: "ATC Ready", description: "Completed ATC Quick Guide", icon: "🛫", color: "#ffaa00", xpReward: 200 },
    { key: "all_modules", name: "Full Course", description: "Completed all 9 modules", icon: "🏆", color: "#ffaa00", xpReward: 500 },
    { key: "streak_7", name: "7-Day Streak", description: "Studied 7 days in a row", icon: "🔥", color: "#ff6b35", xpReward: 150 },
    { key: "streak_30", name: "30-Day Streak", description: "Studied 30 days in a row", icon: "💎", color: "#00d4ff", xpReward: 500 },
    { key: "anpc_certified", name: "ANPC Certified", description: "Aviation & Navigation Procedures", icon: "🏅", color: "#ffaa00", xpReward: 300 },
    { key: "ground_radar", name: "Ground Radar", description: "Ground Radar Systems Expert", icon: "🎯", color: "#00d4ff", xpReward: 250 },
    { key: "quiz_perfect", name: "Perfect Score", description: "100% on any quiz", icon: "⭐", color: "#ffaa00", xpReward: 100 },
  ]).onConflictDoNothing();

  console.log("✅ Seed complete!");
  console.log("   → 9 modules");
  console.log("   → 83 questions (was 25)");
  console.log("   → 10 achievements");
}

seed().catch(console.error);
