import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import * as schema from "./database/schema";

const client = createClient({
  url: process.env.DATABASE_URL!,
  authToken: process.env.DATABASE_AUTH_TOKEN,
});

const db = drizzle(client, { schema });

async function seed() {
  console.log("Clearing existing questions and modules...");
  await db.delete(schema.quizAnswers);
  await db.delete(schema.quizAttempts);
  await db.delete(schema.traineeModuleProgress);
  await db.delete(schema.questions);
  await db.delete(schema.modules);

  console.log("Seeding 6 modules with 10 questions each...");

  const moduleDefs = [
    {
      title: "Introduction to TLS",
      description: "Overview of the Transponder Landing System, its purpose, capabilities, and operational principles.",
      icon: "📡",
      color: "#1e90ff",
      questions: [
        {
          question: "What does TLS stand for?",
          optionA: "Transponder Landing System",
          optionB: "Terminal Landing Sensor",
          optionC: "Tactical Localizer System",
          optionD: "Transmitter Landing Subsystem",
          correctOption: "a",
          explanation: "TLS stands for Transponder Landing System. It provides ILS-equivalent approach guidance by interrogating aircraft SSR transponders.",
        },
        {
          question: "What guidance standard does TLS performance comply with?",
          optionA: "VOR/DME SARPs",
          optionB: "ICAO SARPs for ILS",
          optionC: "FAA Category III MLS requirements",
          optionD: "EUROCAE ED-114 for GBAS",
          correctOption: "b",
          explanation: "TLS performance complies with ICAO SARPs for ILS, Secondary Surveillance Radar, and PAR display standards.",
        },
        {
          question: "Which aircraft equipment does TLS interrogate to determine aircraft position?",
          optionA: "ADS-B OUT transmitter",
          optionB: "VHF navigation receiver",
          optionC: "SSR transponder (Mode C/S)",
          optionD: "DME interrogator",
          correctOption: "c",
          explanation: "TLS interrogates the aircraft's SSR transponder operating in Mode C or Mode S. No new aircraft equipment is required.",
        },
        {
          question: "How many times per second does TLS interrogate an aircraft?",
          optionA: "5",
          optionB: "10",
          optionC: "15",
          optionD: "20",
          correctOption: "d",
          explanation: "TLS interrogates the aircraft 20 times per second to continuously update position and guidance information.",
        },
        {
          question: "What is the first step in the TLS operational sequence?",
          optionA: "Measure time of arrival at multiple antennas",
          optionB: "Interrogate the aircraft transponder",
          optionC: "Transmit ILS guidance signal",
          optionD: "Determine localizer/glide slope deflection",
          correctOption: "b",
          explanation: "The 5-step TLS sequence begins with Step 1: interrogating the aircraft transponder. The aircraft replies, TOA is measured, position is determined, then guidance is transmitted.",
        },
        {
          question: "Over what type of terrain can TLS operate effectively?",
          optionA: "Only flat terrain with no obstacles",
          optionB: "Only elevated terrain",
          optionC: "Any terrain",
          optionD: "Only terrain with existing ILS infrastructure",
          correctOption: "c",
          explanation: "A key advantage of TLS is that it works over any terrain, making it suitable for challenging approach environments.",
        },
        {
          question: "What type of guidance does TLS provide to the flight crew?",
          optionA: "GPS-based vertical guidance only",
          optionB: "ILS-equivalent localizer and glide slope guidance",
          optionC: "Radar altimeter-based guidance",
          optionD: "VOR radial and distance guidance",
          correctOption: "b",
          explanation: "TLS provides ILS-equivalent guidance — both localizer and glide slope — displayed on the aircraft's standard ILS instruments.",
        },
        {
          question: "What is Step 3 in the TLS operational sequence?",
          optionA: "Transmit ILS guidance signal to the aircraft",
          optionB: "Interrogate the aircraft transponder",
          optionC: "Receive transponder replies at multiple antennas and determine x, y, z position",
          optionD: "Calculate course of approach deflection",
          correctOption: "c",
          explanation: "Step 3 is receiving the transponder replies at multiple antennas and using Time of Arrival differences to determine the aircraft's 3D position (x, y, z).",
        },
        {
          question: "Does TLS require new avionics equipment to be installed on the aircraft?",
          optionA: "Yes — a dedicated TLS receiver",
          optionB: "Yes — a modified Mode S transponder",
          optionC: "No — it works with existing SSR transponders",
          optionD: "Yes — an ILS antenna upgrade",
          correctOption: "c",
          explanation: "TLS requires no new aircraft equipment. It uses the aircraft's existing SSR transponder (Mode C or Mode S) which is already standard equipment.",
        },
        {
          question: "Which display standard does TLS guidance presentation comply with?",
          optionA: "MLS azimuth display",
          optionB: "PAR (Precision Approach Radar) display",
          optionC: "TCAS resolution advisory display",
          optionD: "VNAV deviation display",
          correctOption: "b",
          explanation: "TLS performance complies with ICAO SARPs for ILS, Secondary Surveillance, and PAR display, ensuring guidance is presented in a standardized format.",
        },
      ],
    },
    {
      title: "TLS Components and Block Diagram",
      description: "Hardware components of the TLS system including sensors, processors, and transmitters, plus signal flow in the block diagram.",
      icon: "🔧",
      color: "#ff6b35",
      questions: [
        {
          question: "What frequency does the TLS Interrogator Transmitter use to interrogate aircraft?",
          optionA: "1090 MHz",
          optionB: "1030 MHz",
          optionC: "978 MHz",
          optionD: "5031 MHz",
          correctOption: "b",
          explanation: "The TLS Interrogator Transmitter transmits interrogation pulses at 1030 MHz, which is the standard SSR interrogation frequency.",
        },
        {
          question: "On what frequency do aircraft transponders reply to TLS interrogations?",
          optionA: "1030 MHz",
          optionB: "978 MHz",
          optionC: "1090 MHz",
          optionD: "5031 MHz",
          correctOption: "c",
          explanation: "Aircraft transponders reply at 1090 MHz, the standard SSR reply frequency. The TLS sensors receive these 1090 MHz replies.",
        },
        {
          question: "What operating system runs on CPU1 of the TLS system?",
          optionA: "Windows NT",
          optionB: "Windows XP",
          optionC: "QNX",
          optionD: "Linux",
          correctOption: "c",
          explanation: "CPU1 uses an Intel processor running QNX, a real-time operating system suitable for time-critical signal processing tasks.",
        },
        {
          question: "What operating system runs on CPU2 of the TLS system?",
          optionA: "QNX",
          optionB: "Windows NT (WIN-NT)",
          optionC: "Windows XP",
          optionD: "VxWorks",
          correctOption: "b",
          explanation: "CPU2 uses a DEC processor running Windows NT (WIN-NT), handling higher-level processing and guidance computation.",
        },
        {
          question: "What operating system runs on the MIU (Maintenance Interface Unit)?",
          optionA: "QNX",
          optionB: "Windows NT",
          optionC: "Windows XP (WIN-XP)",
          optionD: "DOS",
          correctOption: "c",
          explanation: "The MIU uses an Intel processor running Windows XP, providing the maintenance interface for system monitoring and configuration.",
        },
        {
          question: "Which TLS component provides the calibration and built-in-test function?",
          optionA: "RCU",
          optionB: "MIU",
          optionC: "CAL/BIT",
          optionD: "RSM",
          correctOption: "c",
          explanation: "The CAL/BIT unit provides Calibration and Built-In Test functions, working with the ATA (Airborne Test Antenna) for calibration.",
        },
        {
          question: "What are the two sub-units that make up the Guidance Transmitter?",
          optionA: "CPU1 and CPU2",
          optionB: "Compare and XMTR",
          optionC: "MIU and RCU",
          optionD: "ASA and ESA",
          correctOption: "b",
          explanation: "The Guidance Transmitter consists of the Compare unit (validates guidance signal) and the XMTR (transmitter) which broadcasts ILS-format guidance.",
        },
        {
          question: "What does ASA stand for in TLS component terminology?",
          optionA: "Airborne Sensor Antenna",
          optionB: "Azimuth Sensor Assembly",
          optionC: "Approach Surveillance Array",
          optionD: "Antenna Signal Amplifier",
          correctOption: "b",
          explanation: "ASA stands for Azimuth Sensor Assembly. It is the primary ground-based receive antenna used for measuring the azimuth (lateral) position of the aircraft.",
        },
        {
          question: "What does ESA stand for in TLS component terminology?",
          optionA: "Elevation Sensor Assembly",
          optionB: "Extended Surveillance Antenna",
          optionC: "Encoded Signal Amplifier",
          optionD: "Emergency Standby Assembly",
          correctOption: "a",
          explanation: "ESA stands for Elevation Sensor Assembly. It is mounted on a mast and measures the aircraft's elevation/height for glide slope guidance.",
        },
        {
          question: "In the TLS block diagram, what does the ATA connect to for calibration verification?",
          optionA: "The RCU directly",
          optionB: "The XPNDR signal path via CAL/BIT",
          optionC: "The MIU maintenance port",
          optionD: "The network switch",
          correctOption: "b",
          explanation: "In the block diagram, the ATA (Airborne Test Antenna) feeds into the XPNDR signal path via the CAL/BIT unit, simulating aircraft transponder replies for calibration.",
        },
      ],
    },
    {
      title: "Siting Criteria, Virtual Emanation and Transportable TLS",
      description: "Siting requirements for TLS antennas, the virtual emanation concept, ICAO siting rules, and transportable TLS configuration.",
      icon: "📍",
      color: "#27ae60",
      questions: [
        {
          question: "What is the standard distance from the Threshold Datum (TD) to the ASA sensor?",
          optionA: "TD − 100 m",
          optionB: "TD − 50 m",
          optionC: "TD + 50 m",
          optionD: "TD + 150 m",
          correctOption: "b",
          explanation: "Per Table 2-1 Siting Criteria, the standard siting position for the ASA sensor is TD − 50 m (50 metres before the threshold datum).",
        },
        {
          question: "What is the standard separation between the ASA and ESA sensors?",
          optionA: "50 m",
          optionB: "75 m",
          optionC: "100 m",
          optionD: "150 m",
          correctOption: "c",
          explanation: "The standard ASA-to-ESA separation is 100 m per the TLS siting criteria table (Table 2-1).",
        },
        {
          question: "What is the standard distance from the ESA sensor to the CAL/BIT unit?",
          optionA: "50 m",
          optionB: "100 m",
          optionC: "150 m",
          optionD: "200 m",
          correctOption: "c",
          explanation: "The standard siting distance from the ESA to the CAL/BIT unit is 150 m per the TLS siting table.",
        },
        {
          question: "What is the standard distance from the ASA to the ATA, and what are its limits?",
          optionA: "50 m (min 25 m, max 100 m)",
          optionB: "100 m (min 50 m, max 150 m)",
          optionC: "150 m (min 100 m, max 200 m)",
          optionD: "200 m (min 150 m, max 250 m)",
          correctOption: "b",
          explanation: "The standard ASA-to-ATA distance is 100 m, with a minimum of 50 m and a maximum of 150 m per the siting criteria table.",
        },
        {
          question: "What is the standard ASA-to-ESA angular offset from perpendicular to the runway centerline?",
          optionA: "0° (min 0°, max 5°)",
          optionB: "5° (min 0°, max 10°)",
          optionC: "10° (min 5°, max 15°)",
          optionD: "15° (min 10°, max 20°)",
          correctOption: "b",
          explanation: "The standard ASA-to-ESA angle from perpendicular is 5°, with a minimum of 0° and maximum of 10° per the siting table.",
        },
        {
          question: "What is the standard distance from the ASA sensor to the runway centerline?",
          optionA: "30 m",
          optionB: "45 m",
          optionC: "60 m",
          optionD: "75 m",
          correctOption: "c",
          explanation: "The standard siting distance from the ASA to the runway centerline is 60 m per Table 2-1.",
        },
        {
          question: "What does 'virtual emanation' mean in the context of TLS?",
          optionA: "The guidance signal is transmitted from a virtual server",
          optionB: "The ILS guidance signal appears to originate from a point where no physical antenna exists",
          optionC: "Aircraft compute guidance virtually without receiving a signal",
          optionD: "The system uses virtual reality for controller displays",
          correctOption: "b",
          explanation: "Virtual emanation means the ILS-format guidance signal appears to emanate from the standard ILS antenna position even though no physical TLS antenna is located there.",
        },
        {
          question: "Per ICAO Annex 10 Volume III clause 3.1.3.7.1, where must the ILS localizer antenna be located?",
          optionA: "500 m from the threshold",
          optionB: "1,000 m from the threshold",
          optionC: "2,000 m from the threshold",
          optionD: "At the stop end of the runway",
          correctOption: "c",
          explanation: "ICAO Annex 10 Volume III clause 3.1.3.7.1 requires the ILS localizer to be located 2,000 m from the threshold. TLS uses virtual emanation to satisfy this requirement.",
        },
        {
          question: "On which side(s) of the runway can TLS be sited?",
          optionA: "Left side only",
          optionB: "Right side only",
          optionC: "One or both sides of the runway",
          optionD: "Only on the runway centerline extended",
          correctOption: "c",
          explanation: "TLS can be sited on one or both sides of the runway, providing flexibility depending on terrain and obstacle constraints.",
        },
        {
          question: "What air conditioning system is used in the Transportable TLS shelter?",
          optionA: "Single 15,000 BTU/Hr unit",
          optionB: "Mitsubishi dual 30,700 BTU/Hr units (2 indoor, 2 outdoor compressors)",
          optionC: "Standard rack-mounted 5,000 BTU/Hr coolers",
          optionD: "Passive ventilation only",
          correctOption: "b",
          explanation: "The Transportable TLS uses Mitsubishi dual 30,700 BTU/Hr A/C units — 2 indoor units and 2 outdoor compressors — ensuring adequate cooling in any environment.",
        },
      ],
    },
    {
      title: "Theory of Operation — TOA, DTOA and Software",
      description: "Time of Arrival theory, Difference of Time of Arrival positioning, multipath compensation, and TLS software folder structure.",
      icon: "📐",
      color: "#8e44ad",
      questions: [
        {
          question: "What does a TOA (Time of Arrival) measurement allow TLS to determine?",
          optionA: "Aircraft heading",
          optionB: "Aircraft range (distance) from a sensor",
          optionC: "Aircraft altitude above sea level directly",
          optionD: "Aircraft airspeed",
          correctOption: "b",
          explanation: "TOA (Time of Arrival) measurement gives the range (distance) from the sensor to the aircraft. One TOA defines a sphere of possible positions.",
        },
        {
          question: "What geometric shape does a single DTOA (Difference of Time of Arrival) measurement define?",
          optionA: "A circle",
          optionB: "A sphere",
          optionC: "A hyperbola",
          optionD: "An ellipse",
          correctOption: "c",
          explanation: "A single DTOA measurement defines a hyperbola. The aircraft lies somewhere on this hyperbola formed by two sensors.",
        },
        {
          question: "How many sensors are needed for a complete 3D position fix using DTOA?",
          optionA: "2",
          optionB: "3",
          optionC: "4",
          optionD: "5",
          correctOption: "b",
          explanation: "Three sensors are required for a 3D position fix. With 3 sensors, 2 DTOA pairs yield two intersecting hyperbolas that give a unique 3D position.",
        },
        {
          question: "What is the relationship between angle of incidence and angle of reflection for ground bounce multipath?",
          optionA: "Angle of reflection is twice the angle of incidence",
          optionB: "Angle of incidence equals angle of reflection",
          optionC: "Angle of reflection is half the angle of incidence",
          optionD: "There is no predictable relationship",
          correctOption: "b",
          explanation: "For ground bounce multipath, the angle of incidence equals the angle of reflection, allowing TLS to model and compensate for multipath effects.",
        },
        {
          question: "How does TLS compensate for low-frequency multipath errors?",
          optionA: "By filtering the 1090 MHz signal in hardware",
          optionB: "By using a calibration data file containing a best-fit line",
          optionC: "By increasing the interrogation rate",
          optionD: "By moving the ASA sensor further from the runway",
          correctOption: "b",
          explanation: "Low-frequency multipath is compensated using a calibration data file containing a best-fit line derived from calibration flights, correcting systematic position errors.",
        },
        {
          question: "What does the RCU software control regarding the TLS rack configuration?",
          optionA: "The A/C cooling schedule",
          optionB: "Which rack is designated Primary and which is Reserve",
          optionC: "The interrogation frequency selection",
          optionD: "The UPS battery charging cycle",
          correctOption: "b",
          explanation: "The RCU software controls which rack is active as Primary and which is on Reserve (standby), enabling redundancy and rapid switchover.",
        },
        {
          question: "What are the three main folders on the MIU (Maintenance Interface Unit)?",
          optionA: "C:/System\\, C:/Backup\\, C:/Logs\\",
          optionB: "C:/Archives\\, C:/Run\\, C:/Tools\\",
          optionC: "Home\\TLS\\Run\\, BIT\\, Log\\",
          optionD: "C:/Run\\, C:/Trk\\, C:/Config\\",
          correctOption: "b",
          explanation: "The MIU has three main folders: C:/Archives\\ (archived data), C:/Run\\ (operational files), and C:/Tools\\ (maintenance utilities).",
        },
        {
          question: "What is the path for executable and configuration files in the Base2 software folder structure?",
          optionA: "C:/Run\\",
          optionB: "C:/Archives\\",
          optionC: "Home\\TLS\\Run\\",
          optionD: "BIT\\",
          correctOption: "c",
          explanation: "In the Base2 folder structure, executable and configuration files are in Home\\TLS\\Run\\. Other Base2 folders include BIT\\, Log\\, Raw\\, and Trk\\.",
        },
        {
          question: "Which subsystem measures the aircraft's height for glide slope guidance?",
          optionA: "ASA (Azimuth Sensor Assembly)",
          optionB: "CAL/BIT unit",
          optionC: "ESA (Elevation Sensor Assembly) mast",
          optionD: "Interrogator Transmitter",
          correctOption: "c",
          explanation: "The ESA (Elevation Sensor Assembly), mounted on a mast, forms the Elevation Measurement Subsystem and measures aircraft height.",
        },
        {
          question: "What are the two folders in the RCU software folder structure?",
          optionA: "C:/Archives\\ and C:/Tools\\",
          optionB: "Home\\TLS\\Run\\ and BIT\\",
          optionC: "C:/Run\\ and C:/Trk\\",
          optionD: "C:/Config\\ and C:/Log\\",
          correctOption: "c",
          explanation: "The RCU software folder structure contains two folders: C:/Run\\ (operational files) and C:/Trk\\ (track data files).",
        },
      ],
    },
    {
      title: "Survey, Calibration and Integrity Monitor",
      description: "TLS survey procedures, calibration using LOOK software, FTM verification, and integrity monitoring against ICAO requirements.",
      icon: "🎯",
      color: "#e67e22",
      questions: [
        {
          question: "Which software analyses calibration approach data collected by TLS?",
          optionA: "FTM (Flight Test Monitor)",
          optionB: "LOOK software",
          optionC: "RCU Track software",
          optionD: "Base2 configuration utility",
          correctOption: "b",
          explanation: "LOOK software analyses approach data collected during calibration flights to compute the calibration correction file used by TLS.",
        },
        {
          question: "What is the TLS Calibration Utility software used for?",
          optionA: "Monitoring UPS battery health",
          optionB: "Collecting and managing calibration approach data",
          optionC: "Configuring the network switch",
          optionD: "Programming the transponder code",
          correctOption: "b",
          explanation: "The TLS Calibration Utility software is used during calibration to collect approach data, which is then analysed by LOOK software.",
        },
        {
          question: "What instrument is used alongside the survey procedure to establish sensor positions?",
          optionA: "GPS receiver",
          optionB: "Theodolite",
          optionC: "Laser rangefinder",
          optionD: "Inclinometer",
          correctOption: "b",
          explanation: "A Theodolite is used during the TLS survey procedure to precisely measure sensor positions (CAL/BIT, ATA, ASA, ESA, and Interrogator).",
        },
        {
          question: "What is FTM used for in TLS operations?",
          optionA: "Frequency tuning and modulation",
          optionB: "Flight Test Monitor — verification of localizer and glide slope performance",
          optionC: "Fault tolerance monitoring of the rack",
          optionD: "Field telemetry management",
          correctOption: "b",
          explanation: "FTM (Flight Test Monitor) verifies TLS performance during test approaches, displaying localizer and glide slope deviation vs the ICAO requirement boundary.",
        },
        {
          question: "How is TLS localizer performance graphically displayed during verification?",
          optionA: "As a polar plot of azimuth error vs range",
          optionB: "As microamps (uamps) deviation vs nautical miles from threshold",
          optionC: "As degrees from centerline vs altitude",
          optionD: "As metres cross-track error vs time",
          correctOption: "b",
          explanation: "TLS localizer performance is displayed as microamps (uamps) deviation plotted against distance in nautical miles from the threshold, compared against ICAO limits.",
        },
        {
          question: "What shape represents the ICAO requirement boundary on the FTM glide slope verification graph?",
          optionA: "Circle",
          optionB: "Triangle",
          optionC: "Box or trapezoid",
          optionD: "Sine wave envelope",
          correctOption: "c",
          explanation: "The ICAO requirement for glide slope performance is shown as a box or trapezoid boundary on the FTM approach graphs.",
        },
        {
          question: "What parameter does the TLS integrity monitor primarily monitor for alarms?",
          optionA: "Transponder reply rate",
          optionB: "UPS voltage level",
          optionC: "COA (Course of Approach)",
          optionD: "Interrogator transmit power",
          correctOption: "c",
          explanation: "The TLS integrity monitor is configured to monitor the COA (Course of Approach). If the approach course deviates beyond limits, an alarm is generated.",
        },
        {
          question: "Which components appear in the TLS survey procedure diagram?",
          optionA: "GPS receiver, RTK base station, survey pole",
          optionB: "CAL/BIT, Theodolite, ATA, ASA, ESA, Interrogator",
          optionC: "MIU, RCU, CPU1, CPU2, Network Switch",
          optionD: "UPS, A/C unit, rack, shelter",
          correctOption: "b",
          explanation: "The survey procedure diagram shows positions of: CAL/BIT, Theodolite, ATA, ASA, ESA, and the Interrogator — key elements for accurate sensor geometry.",
        },
        {
          question: "What type of data does calibration collect during approach procedures?",
          optionA: "Weather data and wind shear profiles",
          optionB: "Aircraft approach flight data for position error analysis",
          optionC: "Rack temperature and power consumption logs",
          optionD: "Network latency measurements",
          correctOption: "b",
          explanation: "During calibration, TLS collects aircraft approach data which LOOK software analyses to generate the calibration correction file.",
        },
        {
          question: "What is verified using the FTM approach graphs vs the ICAO requirement boundary?",
          optionA: "Only glide slope performance",
          optionB: "Only localizer performance",
          optionC: "Both glide slope and localizer performance",
          optionD: "Transponder reply rate only",
          correctOption: "c",
          explanation: "FTM approach graphs verify both glide slope and localizer performance against the ICAO requirement box/trapezoid, confirming ILS-equivalent standards.",
        },
      ],
    },
    {
      title: "Operations, Maintenance and Spares",
      description: "TLS operational procedures, maintenance schedule, standard service volume, RCU operations, critical areas, and spare parts.",
      icon: "⚙️",
      color: "#c0392b",
      questions: [
        {
          question: "What is the TLS Standard Service Volume (SSV) plan view coverage?",
          optionA: "±10° to 10 NM and ±25° to 18 NM",
          optionB: "±25° to 10 NM and ±10° to 18 NM",
          optionC: "±35° to 5 NM and ±15° to 10 NM",
          optionD: "±20° to 15 NM only",
          correctOption: "b",
          explanation: "The TLS SSV plan view is ±25° to 10 NM (inner sector) and ±10° to 18 NM (outer sector), matching ILS SSV requirements.",
        },
        {
          question: "What is the TLS Standard Service Volume (SSV) side view coverage?",
          optionA: "0.5°–10° to 10 NM up to 5,000 ft",
          optionB: "1°–7° to 18 NM up to 10,000 ft",
          optionC: "2°–5° to 15 NM up to 8,000 ft",
          optionD: "1°–4° to 25 NM up to 12,000 ft",
          correctOption: "b",
          explanation: "The TLS SSV side view covers 1°–7° elevation angle to 18 NM range, up to 10,000 ft altitude.",
        },
        {
          question: "What is the first action an RCU operator takes when an aircraft intends to use TLS?",
          optionA: "Press ACQUIRE ILS immediately",
          optionB: "Enter the aircraft's transponder code",
          optionC: "Call the aircraft on VHF to confirm approach",
          optionD: "Switch to Reserve rack",
          correctOption: "b",
          explanation: "The RCU operational procedure begins with the operator entering the aircraft's transponder code (squawk code) to identify and track the specific aircraft.",
        },
        {
          question: "When should the RCU operator press ACQUIRE ILS?",
          optionA: "As soon as the aircraft calls inbound",
          optionB: "After verifying the approach matches the published plate and the aircraft is in the service volume",
          optionC: "Only after the aircraft crosses the outer marker",
          optionD: "Immediately upon entering the transponder code",
          correctOption: "b",
          explanation: "The operator ensures the approach matches the published approach plate and the aircraft is in the service volume before pressing ACQUIRE ILS.",
        },
        {
          question: "What display does the RCU provide in Track Mode?",
          optionA: "ATIS weather information",
          optionB: "PAR (Precision Approach Radar) style display",
          optionC: "Standard radar PPI (Plan Position Indicator)",
          optionD: "Strip chart recorder output",
          correctOption: "b",
          explanation: "In Track Mode, the RCU provides a PAR (Precision Approach Radar) style display showing the aircraft's position relative to the approach path.",
        },
        {
          question: "Compared to ILS, how does the TLS critical area footprint compare?",
          optionA: "TLS critical area is larger than ILS",
          optionB: "TLS critical area is the same size as ILS",
          optionC: "TLS critical area is smaller than ILS",
          optionD: "TLS has no critical area requirement",
          correctOption: "c",
          explanation: "The TLS siting footprint (critical area) is smaller than that of a conventional ILS, which is an operational advantage at busy airports.",
        },
        {
          question: "How often should TLS Air Filters be checked per the maintenance schedule (Table 3-1)?",
          optionA: "Annually only",
          optionB: "Every 6 months",
          optionC: "Every 3, 6, 9, and 12 months (quarterly)",
          optionD: "Monthly",
          correctOption: "c",
          explanation: "Per maintenance schedule Table 3-1, task M-5 (Air Filters) is performed at months 3, 6, 9, and 12 — quarterly throughout the year.",
        },
        {
          question: "When is the UPS Battery maintenance check performed per the TLS maintenance schedule?",
          optionA: "Monthly",
          optionB: "Quarterly (months 3, 6, 9, 12)",
          optionC: "At months 6 and 12 (every 6 months)",
          optionD: "Annually only",
          correctOption: "c",
          explanation: "Per maintenance schedule Table 3-1, task M-4 (UPS Battery) is performed at months 6 and 12 — every 6 months.",
        },
        {
          question: "Which maintenance tasks are performed on a monthly basis per Table 3-1?",
          optionA: "UPS Battery check (M-4)",
          optionB: "Guy Wire Tension check (M-6)",
          optionC: "Archive Data Files (M-1) and Critical Areas check (M-3)",
          optionD: "Interrogation TX check (M-10)",
          correctOption: "c",
          explanation: "Per Table 3-1, monthly tasks include M-1 (Archive Data Files) and M-3 (Critical Areas check).",
        },
        {
          question: "Which of the following is listed as a TLS spare part?",
          optionA: "Replacement runway lights",
          optionB: "An entire second rack (hot spare)",
          optionC: "Backup theodolite",
          optionD: "Spare transponder for aircraft",
          correctOption: "b",
          explanation: "TLS spares include: AOA sensor electronics, Cal/BIT unit, obstruction light, and an entire second rack maintained as a hot spare for rapid switchover.",
        },
      ],
    },
  ];

  for (const mod of moduleDefs) {
    console.log(`Creating module: ${mod.title}`);
    const [inserted] = await db
      .insert(schema.modules)
      .values({
        title: mod.title,
        description: mod.description,
        icon: mod.icon,
        color: mod.color,
        order: moduleDefs.indexOf(mod) + 1,
        lessonCount: mod.questions.length,
        isPublished: 1,
      })
      .returning();

    for (let i = 0; i < mod.questions.length; i++) {
      const q = mod.questions[i];
      await db.insert(schema.questions).values({
        moduleId: inserted.id,
        question: q.question,
        optionA: q.optionA,
        optionB: q.optionB,
        optionC: q.optionC,
        optionD: q.optionD,
        correctOption: q.correctOption,
        explanation: q.explanation,
        order: i + 1,
      });
    }

    console.log(`  ✓ ${mod.questions.length} questions added`);
  }

  console.log("\n✅ Seed complete — 6 modules, 60 questions total.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
