import { db } from "./database";
import { modules, questions } from "./database/schema";

const seedData = [
  {
    module: {
      title: "Introduction to TLS",
      description: "Overview of the Transponder Landing System — what it is, how it works, and its operational principles.",
      order: 1,
    },
    questions: [
      {
        question: "What does TLS stand for?",
        optionA: "Transponder Landing System",
        optionB: "Terminal Localizer System",
        optionC: "Tactical Landing Sensor",
        optionD: "Threshold Localizer Signal",
        correctOption: "A",
        explanation: "TLS stands for Transponder Landing System. It provides ILS-equivalent approach guidance by interrogating aircraft SSR transponders.",
        order: 1,
      },
      {
        question: "What type of aircraft equipment does TLS interrogate to determine aircraft position?",
        optionA: "VHF radio transponder",
        optionB: "SSR (Secondary Surveillance Radar) transponder in Mode C or Mode S",
        optionC: "DME transponder",
        optionD: "GPS receiver",
        correctOption: "B",
        explanation: "TLS interrogates the aircraft's existing SSR transponder operating in Mode C or Mode S — no new aircraft equipment is required.",
        order: 2,
      },
      {
        question: "What internationally recognised guidance standard does TLS performance comply with?",
        optionA: "FAA AC 150/5300-18",
        optionB: "ICAO SARPs for ILS, Secondary Surveillance, and PAR display",
        optionC: "EUROCAE ED-114",
        optionD: "MIL-STD-461",
        correctOption: "B",
        explanation: "TLS performance complies with ICAO Standards and Recommended Practices (SARPs) for ILS, Secondary Surveillance Radar, and PAR display.",
        order: 3,
      },
      {
        question: "How many times per second does TLS interrogate the aircraft transponder?",
        optionA: "5 times per second",
        optionB: "10 times per second",
        optionC: "20 times per second",
        optionD: "50 times per second",
        correctOption: "C",
        explanation: "TLS interrogates the aircraft transponder 20 times per second to maintain accurate, continuous position tracking.",
        order: 4,
      },
      {
        question: "What is the first step in the TLS operational sequence?",
        optionA: "Measure Time of Arrival at multiple antennas",
        optionB: "Interrogate the aircraft transponder",
        optionC: "Transmit ILS guidance signals",
        optionD: "Determine LOC/GS deflection",
        correctOption: "B",
        explanation: "Step 1 is to interrogate the aircraft transponder. The sequence is: interrogate → transponder replies → measure TOA → determine position → transmit guidance.",
        order: 5,
      },
      {
        question: "Which step in the TLS sequence involves measuring signals at multiple antennas?",
        optionA: "Step 1",
        optionB: "Step 2",
        optionC: "Step 3",
        optionD: "Step 5",
        correctOption: "C",
        explanation: "Step 3: replies are received at multiple antennas and Time of Arrival (TOA) is measured at each to determine the aircraft's x, y, z position.",
        order: 6,
      },
      {
        question: "What type of terrain or runway limitations does TLS impose on an airfield?",
        optionA: "Requires flat terrain with a minimum 3,000m runway",
        optionB: "Requires a specially prepared runway surface",
        optionC: "Works over any terrain and is suitable for short runways",
        optionD: "Requires a clear 500m approach sector free of obstacles",
        correctOption: "C",
        explanation: "One key advantage of TLS is that it works over any terrain and is suitable for short runways, making it more flexible than conventional ILS.",
        order: 7,
      },
      {
        question: "What guidance output does TLS ultimately transmit to the aircraft cockpit?",
        optionA: "VHF Omni-Range (VOR) bearing",
        optionB: "ILS-equivalent localizer and glide slope deflection signals",
        optionC: "GPS WAAS correction data",
        optionD: "ADF bearing",
        correctOption: "B",
        explanation: "TLS transmits ILS-equivalent localizer (LOC) and glide slope (GS) deflection signals, so pilots use their standard ILS cockpit instruments.",
        order: 8,
      },
      {
        question: "Does installation of TLS require any new avionics or equipment to be fitted to the aircraft?",
        optionA: "Yes — a dedicated TLS receiver must be installed",
        optionB: "Yes — an upgraded Mode S transponder is required",
        optionC: "No — it uses the aircraft's existing SSR transponder",
        optionD: "No — but a software update to the FMS is required",
        correctOption: "C",
        explanation: "No new aircraft equipment is needed. TLS uses the transponder already fitted to the aircraft for ATC secondary surveillance.",
        order: 9,
      },
      {
        question: "What is the final step in the TLS five-step operational sequence?",
        optionA: "Measure TOA at each sensor antenna",
        optionB: "Determine the aircraft's 3D position",
        optionC: "Interrogate the aircraft transponder again",
        optionD: "Determine LOC/GS deflection and transmit ILS guidance",
        correctOption: "D",
        explanation: "Step 5 (the final step): determine LOC and GS deflection from the calculated position and transmit the ILS guidance signals to the aircraft.",
        order: 10,
      },
    ],
  },
  {
    module: {
      title: "TLS Components and Block Diagram",
      description: "Hardware components of the TLS, their functions, operating frequencies, and the system block diagram.",
      order: 2,
    },
    questions: [
      {
        question: "What frequency does the TLS Interrogator Transmitter use to interrogate aircraft transponders?",
        optionA: "978 MHz",
        optionB: "1030 MHz",
        optionC: "1090 MHz",
        optionD: "1176 MHz",
        correctOption: "B",
        explanation: "The TLS Interrogator Transmitter operates at 1030 MHz — the standard SSR interrogation frequency used worldwide.",
        order: 1,
      },
      {
        question: "On what frequency do aircraft transponders reply to TLS interrogations?",
        optionA: "978 MHz",
        optionB: "1030 MHz",
        optionC: "1090 MHz",
        optionD: "1215 MHz",
        correctOption: "C",
        explanation: "Aircraft transponders reply on 1090 MHz — the standard SSR reply frequency. TLS sensors receive these replies to calculate TOA.",
        order: 2,
      },
      {
        question: "What is the function of the ASA Sensor in TLS?",
        optionA: "Transmits ILS localizer signals to the aircraft",
        optionB: "Receives transponder replies and measures Time of Arrival for azimuth determination",
        optionC: "Controls the UPS and power distribution",
        optionD: "Provides the operator interface for approach monitoring",
        correctOption: "B",
        explanation: "The ASA (Azimuth Sensor Array) receives 1090 MHz transponder replies and measures Time of Arrival to determine the aircraft's azimuth position.",
        order: 3,
      },
      {
        question: "What operating system runs on the TLS CPU1 processor?",
        optionA: "Windows XP",
        optionB: "Windows NT",
        optionC: "QNX",
        optionD: "Linux",
        correctOption: "C",
        explanation: "CPU1 uses an Intel processor running QNX — a real-time operating system chosen for its deterministic performance in safety-critical applications.",
        order: 4,
      },
      {
        question: "What operating system runs on the TLS CPU2 processor?",
        optionA: "QNX",
        optionB: "Windows NT",
        optionC: "Windows XP",
        optionD: "MS-DOS",
        correctOption: "B",
        explanation: "CPU2 uses a DEC processor running Windows NT. CPU1 (QNX) handles real-time processing while CPU2 (WIN-NT) handles higher-level functions.",
        order: 5,
      },
      {
        question: "What operating system is used on both the MIU and RCU workstations?",
        optionA: "QNX",
        optionB: "Windows NT",
        optionC: "Windows XP",
        optionD: "Windows 7",
        correctOption: "C",
        explanation: "Both the MIU (Maintenance Interface Unit) and RCU (Remote Control Unit) use Intel processors running Windows XP.",
        order: 6,
      },
      {
        question: "What is the role of the CAL/BIT unit in TLS?",
        optionA: "It provides UPS battery backup to the rack",
        optionB: "It acts as a calibration transponder and Built-In Test source",
        optionC: "It controls the guidance transmitter output power",
        optionD: "It stores archived approach data files",
        correctOption: "B",
        explanation: "The CAL/BIT unit is used as a calibration transponder and Built-In Test (BIT) source. It appears in the block diagram in the ATA→XPNDR calibration flow.",
        order: 7,
      },
      {
        question: "Which TLS component transmits the final ILS-equivalent guidance signals toward the aircraft?",
        optionA: "Interrogator Transmitter",
        optionB: "ASA Sensor",
        optionC: "Guidance Transmitter (XMTR)",
        optionD: "RSM",
        correctOption: "C",
        explanation: "The Guidance Transmitter (XMTR), part of the Guidance Transmitter subsystem alongside the Compare unit, transmits the ILS-equivalent LOC and GS signals.",
        order: 8,
      },
      {
        question: "What is the function of the ESA Sensor in TLS?",
        optionA: "It transmits the SSR interrogation pulses",
        optionB: "It measures aircraft elevation (height) using a mast-mounted antenna",
        optionC: "It provides the network switching between racks",
        optionD: "It stores the calibration data files",
        correctOption: "B",
        explanation: "The ESA (Elevation Sensor Array) is mounted on a mast and measures the aircraft's elevation (height), contributing to the 3D position fix.",
        order: 9,
      },
      {
        question: "What does the Rack Switch Controller do in the TLS system?",
        optionA: "Switches between QNX and Windows NT operating modes",
        optionB: "Controls which rack (Primary or Reserve) is active",
        optionC: "Switches the interrogation frequency between 1030 and 978 MHz",
        optionD: "Controls power to the outdoor antenna elements",
        correctOption: "B",
        explanation: "The Rack Switch Controller manages switchover between the Primary and Reserve racks, working with the RCU software to maintain system availability.",
        order: 10,
      },
    ],
  },
  {
    module: {
      title: "Siting Criteria, Virtual Emanation and Transportable TLS",
      description: "How and where TLS equipment is sited relative to the runway, the concept of virtual emanation, and the transportable TLS shelter configuration.",
      order: 3,
    },
    questions: [
      {
        question: "According to TLS Table 2-1, what is the standard distance from the ASA sensor to the Touchdown Zone (TD)?",
        optionA: "TD minus 100m",
        optionB: "TD minus 50m",
        optionC: "TD plus 50m",
        optionD: "TD plus 150m",
        correctOption: "B",
        explanation: "Table 2-1 specifies the standard ASA position as TD−50m (Touchdown Zone minus 50 metres), with that being the standard siting value.",
        order: 1,
      },
      {
        question: "What is the standard separation distance between the ASA and ESA sensors?",
        optionA: "50 metres",
        optionB: "75 metres",
        optionC: "100 metres",
        optionD: "150 metres",
        correctOption: "C",
        explanation: "Per Table 2-1, the standard ASA-to-ESA separation is 100 metres, enabling the system to accurately resolve aircraft elevation.",
        order: 2,
      },
      {
        question: "What is the standard distance from the ESA sensor to the CAL/BIT unit?",
        optionA: "50 metres",
        optionB: "100 metres",
        optionC: "150 metres",
        optionD: "200 metres",
        correctOption: "C",
        explanation: "Table 2-1 specifies a standard ESA-to-CAL/BIT distance of 150 metres for correct system geometry during calibration.",
        order: 3,
      },
      {
        question: "What is the standard (and minimum/maximum) distance from the ASA sensor to the ATA?",
        optionA: "Standard 100m (min 50m, max 150m)",
        optionB: "Standard 75m (min 25m, max 100m)",
        optionC: "Standard 150m (min 100m, max 200m)",
        optionD: "Standard 50m (min 10m, max 100m)",
        correctOption: "A",
        explanation: "Table 2-1: ASA to ATA standard = 100m, minimum = 50m, maximum = 150m.",
        order: 4,
      },
      {
        question: "What is the standard angle of the ASA-ESA baseline from the runway perpendicular?",
        optionA: "0° (exactly perpendicular)",
        optionB: "5° (min 0°, max 10°)",
        optionC: "10° (min 5°, max 15°)",
        optionD: "15° (min 10°, max 20°)",
        correctOption: "B",
        explanation: "Table 2-1: The ASA-ESA angle from perpendicular to the runway centreline is standard 5°, minimum 0°, maximum 10°.",
        order: 5,
      },
      {
        question: "What is the standard lateral distance from the ASA sensor to the runway centreline?",
        optionA: "30 metres",
        optionB: "45 metres",
        optionC: "60 metres",
        optionD: "90 metres",
        correctOption: "C",
        explanation: "Table 2-1 specifies a standard ASA-to-centreline distance of 60 metres.",
        order: 6,
      },
      {
        question: "What does 'virtual emanation' mean in the context of TLS?",
        optionA: "The guidance signal appears to come from a physical antenna at the threshold",
        optionB: "The ILS guidance signal appears to originate from a point where no physical antenna is located",
        optionC: "The interrogator transmits from multiple virtual antennas simultaneously",
        optionD: "The system uses virtual routing to send guidance via the network switch",
        correctOption: "B",
        explanation: "Virtual emanation means the TLS guidance signal appears to originate from a calculated point (e.g. the standard ILS localizer position) where no physical TLS antenna exists.",
        order: 7,
      },
      {
        question: "Per ICAO Annex 10 Vol III (3.1.3.7.1), where must the ILS localizer antenna be located?",
        optionA: "At least 500m from the runway threshold",
        optionB: "At least 1,000m from the runway threshold",
        optionC: "At least 2,000m from the runway threshold",
        optionD: "At least 3,000m from the runway threshold",
        correctOption: "C",
        explanation: "ICAO Annex 10 Vol III section 3.1.3.7.1 requires the ILS localizer antenna to be at least 2,000m from the threshold. TLS virtual emanation can replicate this without a physical antenna at that point.",
        order: 8,
      },
      {
        question: "On which side(s) of the runway can TLS equipment be sited?",
        optionA: "Only on the left side (pilot's view on approach)",
        optionB: "Only on the right side",
        optionC: "Only on the centreline extension",
        optionD: "On one side or both sides of the runway",
        correctOption: "D",
        explanation: "TLS can be sited on one side or both sides of the runway, providing flexibility for airfields with differing obstacle and terrain environments.",
        order: 9,
      },
      {
        question: "What air conditioning system is fitted to the transportable TLS shelter?",
        optionA: "A single 15,000 BTU/Hr split unit",
        optionB: "Mitsubishi dual 30,700 BTU/Hr units (2 indoor, 2 outdoor compressors)",
        optionC: "A redundant 50,000 BTU/Hr central system",
        optionD: "No dedicated A/C — passive cooling only",
        correctOption: "B",
        explanation: "The transportable TLS shelter uses a Mitsubishi dual A/C system rated at 30,700 BTU/Hr each, with 2 indoor units and 2 outdoor compressors.",
        order: 10,
      },
    ],
  },
  {
    module: {
      title: "TLS Theory — TOA, DTOA and Software Folder Structure",
      description: "The mathematical theory behind Time of Arrival (TOA) and Difference of Time of Arrival (DTOA) positioning, multipath effects, and the TLS software folder structure.",
      order: 4,
    },
    questions: [
      {
        question: "What does a single Time of Arrival (TOA) measurement define geometrically?",
        optionA: "A single point in 3D space",
        optionB: "A straight line from sensor to aircraft",
        optionC: "A sphere (range) centred on the sensor",
        optionD: "A hyperbola around two sensors",
        correctOption: "C",
        explanation: "A single TOA measurement gives the range from that sensor to the aircraft — geometrically a sphere. Two TOA values give two spheres whose intersection narrows position.",
        order: 1,
      },
      {
        question: "What geometric shape does a Difference of Time of Arrival (DTOA) measurement produce?",
        optionA: "A circle",
        optionB: "A hyperbola",
        optionC: "An ellipse",
        optionD: "A straight line",
        correctOption: "B",
        explanation: "DTOA (the difference in arrival times at two sensors) defines a hyperbola — the locus of points with a constant range difference from two foci.",
        order: 2,
      },
      {
        question: "How many sensors are required to achieve a full 3D position fix of the aircraft?",
        optionA: "1 sensor",
        optionB: "2 sensors",
        optionC: "3 sensors",
        optionD: "4 sensors",
        correctOption: "C",
        explanation: "Three sensors (providing three DTOA measurements) are required to uniquely determine a 3D position (x, y, z) of the aircraft.",
        order: 3,
      },
      {
        question: "Which TLS subsystem is specifically responsible for measuring the aircraft's height (elevation)?",
        optionA: "ASA (Azimuth Sensor Array)",
        optionB: "CAL/BIT unit",
        optionC: "ESA mast (Elevation Sensor Array)",
        optionD: "ATA (Airborne Test Aircraft)",
        correctOption: "C",
        explanation: "The ESA mast — the Elevation Sensor Array — is the subsystem that measures aircraft height, contributing the elevation dimension to the 3D position solution.",
        order: 4,
      },
      {
        question: "In ground bounce multipath, what is the relationship between the angle of incidence and the angle of reflection?",
        optionA: "The angle of reflection is twice the angle of incidence",
        optionB: "The angle of incidence equals the angle of reflection",
        optionC: "The angle of reflection is half the angle of incidence",
        optionD: "There is no fixed relationship — it depends on surface type",
        correctOption: "B",
        explanation: "Classic specular reflection: angle of incidence = angle of reflection. This is how ground bounce multipath propagates to the TLS sensors.",
        order: 5,
      },
      {
        question: "How does TLS compensate for low-frequency multipath errors?",
        optionA: "By using a higher interrogation frequency",
        optionB: "By fitting absorbing panels around each sensor",
        optionC: "Using a calibration data file (best-fit line) derived from calibration approaches",
        optionD: "By filtering all signals below 500 Hz",
        correctOption: "C",
        explanation: "Low-frequency multipath is compensated using a calibration data file containing a best-fit line derived during the calibration process.",
        order: 6,
      },
      {
        question: "What software tool is used to analyse calibration approach data collected by TLS?",
        optionA: "FTM (Flight Test Monitor)",
        optionB: "LOOK software",
        optionC: "RCU Track Mode",
        optionD: "Base2",
        correctOption: "B",
        explanation: "The LOOK software analyses the calibration data (approach data files) collected during calibration flights.",
        order: 7,
      },
      {
        question: "Which folder on the MIU workstation stores the main TLS executable and configuration files?",
        optionA: "C:/Run\\",
        optionB: "C:/Archives\\",
        optionC: "C:/Tools\\",
        optionD: "C:/Trk\\",
        correctOption: "A",
        explanation: "The MIU has three main folders: C:/Archives\\ (archived data), C:/Run\\ (executables and config), and C:/Tools\\ (utilities).",
        order: 8,
      },
      {
        question: "On the Base2 system, which sub-folder contains the executable and configuration files?",
        optionA: "Home\\TLS\\BIT\\",
        optionB: "Home\\TLS\\Log\\",
        optionC: "Home\\TLS\\Run\\",
        optionD: "Home\\TLS\\Raw\\",
        correctOption: "C",
        explanation: "The Base2 folder structure: Home\\TLS\\Run\\ holds exec+config files. Other sub-folders include BIT\\, Log\\, Raw\\, and Trk\\.",
        order: 9,
      },
      {
        question: "What does the RCU software control regarding the TLS racks?",
        optionA: "It manages the A/C temperature in each rack",
        optionB: "It controls which rack (Primary or Reserve) is active",
        optionC: "It upgrades firmware on each rack automatically",
        optionD: "It controls the UPS charge cycles for both racks",
        correctOption: "B",
        explanation: "The RCU (Remote Control Unit) software controls the active rack — switching between the Primary rack and Reserve rack as required.",
        order: 10,
      },
    ],
  },
  {
    module: {
      title: "Survey, Calibration and Integrity Monitor",
      description: "The TLS survey procedure, calibration using the TLS Calibration Utility, Flight Test Monitor (FTM) verification, and integrity monitoring configuration.",
      order: 5,
    },
    questions: [
      {
        question: "Which of the following is positioned at the Theodolite location during the TLS survey procedure?",
        optionA: "The CAL/BIT unit only",
        optionB: "A standard surveying theodolite to align the sensor baseline",
        optionC: "The FTM laptop",
        optionD: "The RCU workstation",
        correctOption: "B",
        explanation: "The survey procedure diagram shows the theodolite positioned to align the ASA, ESA, ATA, and Interrogator — standard surveying practice for TLS sensor geometry.",
        order: 1,
      },
      {
        question: "What software is used to perform TLS calibration?",
        optionA: "LOOK software",
        optionB: "Base2",
        optionC: "TLS Calibration Utility",
        optionD: "RCU Track Mode",
        correctOption: "C",
        explanation: "TLS calibration is performed using the TLS Calibration Utility software, which guides the technician through the calibration data collection process.",
        order: 2,
      },
      {
        question: "What does FTM stand for and what is it used for in TLS?",
        optionA: "Frequency Test Mode — tests interrogation frequency accuracy",
        optionB: "Flight Test Monitor — used to verify TLS guidance performance against ICAO requirements",
        optionC: "Final Track Module — final software module loaded during commissioning",
        optionD: "Field Test Meter — handheld RF power measurement tool",
        correctOption: "B",
        explanation: "FTM = Flight Test Monitor. It is used during verification to compare TLS localizer and glide slope performance against ICAO requirement boxes/trapezoids on approach graphs.",
        order: 3,
      },
      {
        question: "How is TLS localizer performance typically displayed during FTM verification?",
        optionA: "As dBm vs range in kilometres",
        optionB: "As microamps (uamps) vs nautical miles",
        optionC: "As degrees deviation vs altitude in feet",
        optionD: "As volts vs time in seconds",
        correctOption: "B",
        explanation: "TLS localizer performance is displayed as microamps (uamps) vs nautical miles, and must remain within the ICAO requirement box/trapezoid.",
        order: 4,
      },
      {
        question: "What parameter does the TLS Integrity Monitor specifically alarm on?",
        optionA: "Rack temperature exceeding 40°C",
        optionB: "GPS time reference loss",
        optionC: "COA (Course of Approach)",
        optionD: "UPS battery voltage drop",
        correctOption: "C",
        explanation: "The Integrity Monitor is configured to alarm on COA (Course of Approach) — monitoring that the transmitted guidance remains on the correct approach path.",
        order: 5,
      },
      {
        question: "Which components are shown in the TLS survey procedure diagram?",
        optionA: "CPU1, CPU2, MIU, RCU, RSM",
        optionB: "CAL/BIT, Theodolite, ATA, ASA, ESA, Interrogator",
        optionC: "Guidance XMTR, Network Switch, Rack Switch Controller",
        optionD: "UPS, PDU, A/C units, shelter",
        correctOption: "B",
        explanation: "The survey procedure diagram shows the positions of: CAL/BIT, Theodolite location, ATA, ASA, ESA, and the Interrogator.",
        order: 6,
      },
      {
        question: "What type of data does calibration primarily collect from the aircraft?",
        optionA: "FMS navigation log data",
        optionB: "Approach data (TOA measurements during calibration approaches)",
        optionC: "Radar return data from the ASA",
        optionD: "ILS deviation recordings from the aircraft ADC",
        correctOption: "B",
        explanation: "During calibration, approach data (TOA measurements as the aircraft flies calibration approaches) is collected and then analysed by LOOK software.",
        order: 7,
      },
      {
        question: "Against what standard are TLS glide slope and localizer FTM results compared?",
        optionA: "The manufacturer's factory test specification",
        optionB: "The ICAO requirement box/trapezoid on the approach graph",
        optionC: "FAA AC 43.13 tolerance tables",
        optionD: "The airport's local procedure design gradient",
        correctOption: "B",
        explanation: "FTM approach graphs show TLS performance plotted against the ICAO requirement box (localizer) or trapezoid (glide slope) to confirm compliance.",
        order: 8,
      },
      {
        question: "Why is survey accuracy particularly important for TLS?",
        optionA: "Because the shelter must align with the magnetic north reference",
        optionB: "Because sensor geometry directly affects the accuracy of the TOA-based position calculation",
        optionC: "Because the UPS must be level to within 0.5°",
        optionD: "Because the network cables have a maximum bend radius dependent on layout",
        correctOption: "B",
        explanation: "Accurate survey of sensor positions is critical because TLS position calculation relies on precise known geometry between sensors — errors in survey translate directly to errors in aircraft position.",
        order: 9,
      },
      {
        question: "What is the purpose of the ATA (Airborne Test Aircraft transponder) in the TLS calibration context?",
        optionA: "It is an aircraft permanently assigned to calibration flights only",
        optionB: "It is a ground-based reference transponder used to test the system before flight calibration",
        optionC: "It replicates transponder replies from a known ground position for system testing",
        optionD: "Both B and C — a ground reference transponder at a known position",
        correctOption: "D",
        explanation: "The ATA (also referred to in the block diagram ATA→XPNDR flow) is a ground-based reference transponder at a surveyed position, used to verify system performance before and after flight calibration.",
        order: 10,
      },
    ],
  },
  {
    module: {
      title: "Operations, Maintenance and Spares",
      description: "TLS operational procedures, the maintenance schedule, critical areas, Standard Service Volume coverage, and spare parts.",
      order: 6,
    },
    questions: [
      {
        question: "What is the first action an RCU operator takes when an aircraft calls for a TLS approach?",
        optionA: "Press ACQUIRE ILS immediately",
        optionB: "Enter the aircraft transponder code into the RCU",
        optionC: "Switch to Reserve rack",
        optionD: "Activate the CAL/BIT",
        correctOption: "B",
        explanation: "The RCU procedure: enter the aircraft's transponder (squawk) code first, ensure the approach matches the published plate, then press ACQUIRE ILS when the aircraft is in the service volume.",
        order: 1,
      },
      {
        question: "When should the RCU operator press the ACQUIRE ILS button?",
        optionA: "As soon as the aircraft checks in on frequency",
        optionB: "When the aircraft is within the TLS Standard Service Volume",
        optionC: "Only after the aircraft has passed the outer marker",
        optionD: "When the aircraft is on final at 5 NM",
        correctOption: "B",
        explanation: "The procedure requires pressing ACQUIRE ILS when the aircraft is in the service volume — not before, to ensure TLS can acquire and track the correct transponder.",
        order: 2,
      },
      {
        question: "What does maintenance task M-5 cover, and how often is it performed?",
        optionA: "UPS Battery check — every 6 months",
        optionB: "Air Filter cleaning/replacement — months 3, 6, 9, 12 (quarterly)",
        optionC: "Guy Wire Tension check — annually",
        optionD: "Archive Data Files — monthly",
        correctOption: "B",
        explanation: "Per Table 3-1: M-5 = Air Filters, performed at months 3, 6, 9, and 12 (quarterly). Blocked filters can cause rack overheating.",
        order: 3,
      },
      {
        question: "How frequently must the M-1 Archive Data Files task be performed?",
        optionA: "Weekly",
        optionB: "Monthly",
        optionC: "Every 3 months",
        optionD: "Annually",
        correctOption: "B",
        explanation: "Table 3-1: M-1 Archive Data Files is a monthly maintenance task.",
        order: 4,
      },
      {
        question: "Which maintenance tasks (per Table 3-1) are performed at 6-month and 12-month intervals?",
        optionA: "M-1 (Archive) and M-5 (Air Filters)",
        optionB: "M-4 (UPS Battery) and M-6 (Guy Wire Tension)",
        optionC: "M-9 (Clean/Inspect) and M-10 (Interrogation TX)",
        optionD: "M-3 (Critical Areas) and M-11 (Guidance TX)",
        correctOption: "B",
        explanation: "Table 3-1: M-4 (UPS Battery check) and M-6 (Guy Wire Tension check) are both performed at months 6 and 12.",
        order: 5,
      },
      {
        question: "How does the TLS critical area footprint compare to that of a conventional ILS?",
        optionA: "TLS critical area is larger than ILS",
        optionB: "TLS critical area is the same as ILS",
        optionC: "TLS siting footprint is smaller than ILS",
        optionD: "TLS has no defined critical area",
        correctOption: "C",
        explanation: "A key TLS advantage: its siting footprint (and associated critical area) is smaller than that of a conventional ILS, reducing restrictions on vehicle and aircraft movements near the runway.",
        order: 6,
      },
      {
        question: "What is the plan view coverage of the TLS Standard Service Volume (SSV)?",
        optionA: "±10° to 10 NM and ±25° to 18 NM",
        optionB: "±25° to 10 NM and ±10° to 18 NM",
        optionC: "±35° to 10 NM only",
        optionD: "±15° to 25 NM",
        correctOption: "B",
        explanation: "The TLS SSV plan view: ±25° out to 10 NM, then narrowing to ±10° out to 18 NM — matching the ILS coverage standard.",
        order: 7,
      },
      {
        question: "What is the side view (elevation) coverage of the TLS Standard Service Volume?",
        optionA: "0.5° to 5° up to 10 NM, up to 5,000 ft",
        optionB: "1° to 7° out to 18 NM, up to 10,000 ft",
        optionC: "3° to 10° out to 25 NM, up to 15,000 ft",
        optionD: "2° to 8° out to 15 NM, up to 8,000 ft",
        correctOption: "B",
        explanation: "The TLS SSV side (elevation) view: 1° to 7° elevation angle out to 18 NM, up to a maximum of 10,000 ft.",
        order: 8,
      },
      {
        question: "Which of the following is listed as a TLS spare item?",
        optionA: "A spare Theodolite",
        optionB: "A spare GPS receiver",
        optionC: "An entire second rack (hot spare)",
        optionD: "A spare shelter A/C compressor only",
        correctOption: "C",
        explanation: "TLS spares include: AOA sensor electronics, Cal/BIT unit, and an entire second rack kept as a hot spare — plus the obstruction light.",
        order: 9,
      },
      {
        question: "What display mode does the RCU use to show aircraft position during an active TLS approach?",
        optionA: "Radar PPI (Plan Position Indicator)",
        optionB: "PAR (Precision Approach Radar) display in Track Mode",
        optionC: "FTM approach graph",
        optionD: "LOOK software plot",
        correctOption: "B",
        explanation: "During an active approach, the RCU operates in Track Mode showing a PAR (Precision Approach Radar)-style display so the controller can monitor the aircraft's progress.",
        order: 10,
      },
    ],
  },
];

async function seed() {
  console.log("Clearing existing data...");
  await db.delete(questions);
  await db.delete(modules);

  console.log("Seeding 6 modules...");
  for (const item of seedData) {
    const [inserted] = await db
      .insert(modules)
      .values({
        title: item.module.title,
        description: item.module.description,
        order: item.module.order,
      })
      .returning();

    console.log(`  Module ${inserted.order}: ${inserted.title}`);

    for (const q of item.questions) {
      await db.insert(questions).values({
        moduleId: inserted.id,
        question: q.question,
        optionA: q.optionA,
        optionB: q.optionB,
        optionC: q.optionC,
        optionD: q.optionD,
        correctOption: q.correctOption,
        explanation: q.explanation,
        order: q.order,
      });
    }
    console.log(`    → ${item.questions.length} questions inserted`);
  }

  console.log("\nDone! 6 modules, 60 questions total.");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
